NCAR/ParallelIO

src/flib/pio_support.F90, src/flib/piolib_mod.F90, tests/performance/pioperformance.F90
for fortran support functions.
=> Added and improved some doxygen documentation

src/clib/pio_darray.c, src/clib/pio_file.c
=> Added documentation hooks to help the doxygen api page 

doc/source/mach_walkthrough.txt
Only one file has changes, mach_walkthrough.txt. I have added build instructions for Linux.
=> added build instructions for Linux, from source code

examples/c/example2.c, src/clib/pio.h, src/clib/pio_nc4.c, tests/unit/CMakeLists.txt, tests/unit/test_nc4.c
I accidently checked the implementation into master, look at src/clib/pio_nc4.c.
=> Tests for PIOc_inq/def_var_chunking

examples/c/example1.c, examples/c/example2.c, examples/c/examplePio.c
Bug fix for compile problems in examples when timing turned off.
=> fixed compile problem when timing turned off

src/clib/pio_file.c, tests/unit/test_intercomm.c
More pio_file.c cleanup, also turned test of PIOc_deletefile back on.
=> Ejh cleanup6

src/clib/pio_file.c, tests/unit/test_intercomm.c
=> Revert "Ejh cleanup6"

doc/source/Error.txt, src/clib/pio_darray.c, tests/unit/test_nc4.c
Also cleanup of warnings in nc_test4.
No code changes for pio_darray, just documentation and spacing. Getting ready to add async IO to this code...
=> documentation and spacing cleanup

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_get_nc_async.c, src/clib/pio_internal.h, src/clib/pio_nc4.c, src/clib/pio_nc_async.c, src/clib/pio_put_nc_async.c, src/clib/pioc.c
Cleanup and documentation changes. Applied emacs indent-region to get consistent C-code indents.
=> Ejh darray3

doc/source/mach_walkthrough.txt, src/clib/pio_msg.c, src/clib/pio_put_nc_async.c, src/clib/pioc.c, tests/unit/CMakeLists.txt, tests/unit/test_intercomm2.c
I ran some tests under valgrind and found some memory leaks in the async code. This pull request fixes them.
Valgrind testing will continue on a new branch after this is merged.
=> Memory leaks fixes for async code

src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_lists.c, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_rearrange.c, src/clib/pio_varm.c, src/clib/pioc.c, src/clib/pioc_support.c
This commit adds more argument and return value checks in the
code. Also adding more description for some failure scenarios.
* Stricter argument value (null, invalid args) checks
* Checks for memory allocation errors (malloc/calloc/bget)
=> More argument and return val checks

src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_lists.c, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_rearrange.c, src/clib/pio_varm.c, src/clib/pioc.c, src/clib/pioc_support.c
I was hasty in approving this PR, my apologies to all concerned.   
Reverts NCAR/ParallelIO#112
=> Revert "More argument and return val checks"

doc/source/base.txt, doc/source/code_style.txt
As discussed I have added a short document describing code style for contributors to the C library. (I have left the Fortran library for another programmer who spends more time in that language.)
Best way to read this is to do a make doc and look at the HTML output.
The point of this document is not to teach about good C programming, but just to provide a very basic style guide so that the code looks consistent everywhere. A short (but complete) function from the code base is provided as an example.
This PR is documentation only, with no code changes.
=> added code document

tests/general/CMakeLists.txt, tests/general/pio_decomp_tests_2d.F90.in, tests/general/util/pio_tutil.F90
Adding tests with 2d arrays to test pio write, read and pio_init
options (stride, number of io tasks, aggregators)
=> Adding tests for 2d arrays

src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_msg.c
THis is a continuation of the parameter checking/asserts work. (Not quite complete - there will be one more PR after this one.)
I also fixed the documentation on the functions in these files.
I also removed some very detailed logging that I had put in there while hunting down the recent ncid issues. I left in some higher-level logging, but took out some extra detail.
=> added asserts, cleaned up documentation

src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c
Here are some more of the asserts and return value checks ported from @jayeshkrishna PR.
I have some questions about error handling - please take a look at the code.
=> more asserts and return value checks, with some questions

src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_internal.h, src/clib/pioc_support.c
This is the final round of value checking and asserts.
Some of the netCDF calls are not yet checked. As I add the async code, this checking will change, so I will catch those return codes then.
Fixes #136.
=> Final round of value checking and asserts

tests/general/CMakeLists.txt, tests/general/pio_decomp_tests.F90.in, tests/general/pio_decomp_tests_2d.F90.in, tests/general/pio_decomp_tests_3d.F90.in, tests/general/util/pio_tutil.F90
* Adding test to check reuse of pio decompositions
* Adding more 2d tests
* Adding a simple 3d test
* Corresponding testing infrastructure changes
=> More 1d, 2d and 3d tests

CTestScript.cmake, cmake/LibMPI.cmake, cmake/mpiexec.nwscla, ctest/CTestEnvironment-nwscla.cmake, ctest/runcdash-nwscla-intel.sh, ctest/runctest-nwscla.sh
Added support for Laramie (the Cheyenne testing cluster) nightly tests in cdash on the Intel compiler.
=> Changes to add cdash tests to Laramie

tests/general/CMakeLists.txt, tests/general/pio_decomp_frame_tests.F90.in
This test writes out a 4d (one unlimited dim) array and reads
it back. Each frame is a 3d col decomposed data.
=> Adding a test with unlimited dim

src/clib/CMakeLists.txt, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h
When I made the async changes I did not properly carry forward the doxygen documentation for all the get/put functions.
This PR addresses this problem for the gets. The puts will be done in a future PR.
Note these are documentation changes only - no code was changed, though some was moved to a new file.
=> documentation fixes

doc/CMakeLists.txt, src/clib/pio_internal.h, src/clib/pio_nc.c, src/clib/pioc_support.c
No code changes. Just moved some documentation to internal or external API files, and added documentation for some functions that were not properly documented.
=> more documentation repair

src/clib/pio_nc.c
No code changes, only documentation fixes.
Fixes #159.
=> more documentation fixes

tests/general/README.md, tests/general/util/pio_tutil.F90
Adding command line option to set PIO logging level for tests.
Also adding some related docs.
=> Adding PIO logging option for tests

tests/general/util/pio_tf_f90gen.pl
=> update to work with newer perl versions

CTestScript.cmake, cmake/LibMPI.cmake, ctest/runctest-cgd.sh, ctest/runctest-nersc.sh
Updating comments. No code changes.
Fixes #176.
=> Updating some comments that contain wrong platform names

tests/general/ncdf_fail.F90.in, tests/general/pio_file_simple_tests.F90.in, tests/general/pio_iosystem_tests.F90.in, tests/general/pio_iosystem_tests2.F90.in, tests/general/pio_iosystem_tests3.F90.in, tests/general/test_memleak.c, tests/general/util/pio_tf_f90gen.pl, tests/general/util/pio_tutil.F90
Remove whitespace and untabify files - formating changes only.
=> reformat files in tests/general

src/flib/pio_nf.F90, src/flib/pio_types.F90, src/flib/piodarray.F90.in, src/flib/piolib_mod.F90, src/flib/pionfatt_mod.F90.in, src/flib/pionfget_mod.F90.in, src/flib/pionfput_mod.F90.in
Formating changes only - remove extra whitespace and untabify files.
=> format clean flib files

doc/source/mach_walkthrough.txt
Some minor changes to update the build for new HDF5 and netCDF versions.
No code changes, just documentation.
=> updated build documentation

src/clib/pio_rearrange.c
Documentation and whitespace cleanup of pio_rearranger.c.
=> documentation and whitespace cleanup

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_lists.c, src/clib/pioc.c
Added comments and cleaned up code.
There are some questions about fields in pio.h, marked with "???". Please go review that file, and see if you can fill in any of the missing comments. Put them in the code review and I will add them to the file.
=> whitespace changes only

tests/unit/pio_tests.h, tests/unit/test_darray.c
=> repair and further development of test

ctest/runcdash-nwscla-intel.sh
Just changed the pnetcdf module name
=> Changes to support nightly tests on laramie

src/clib/pio_nc4.c
=> update error handling in pio_nc4.c

src/clib/pio_darray_int.c, src/clib/pioc.c, tests/unit/test_darray.c
In this PR I got the simple test_darray to work, writing and then reading a distributed array.
The next step will be to add an async version of this test. This is work for #89.
=> got simple (non-async) darray test working

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_nc4.c
There are numerous "???" in the comments for the elements of structs io_region, io_desc_t, and wmulti_buffer.
In pio_darray.c there are also some "???" where I don't know what comment to put.
Can you use this review to tell me what these comments should be?
=> need some comments in pio.h

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, src/clib/pio_spmd.c, src/clib/pioc_support.c
I am adding comments and cleaning up whitespace issues as I study this code.
More to come, but let's get these changes merged...
No code changes in this PR, except whitespace stuff.
Still plenty of "???" in the code - feel free to use the code review to help me fill in missing comments.
Also took out all casts of the return value of bget(). Since bget() returns void *, there is no need to cast it. It will auto-cast to whatever you assign it to.
=> Adding comments and cleaning up whitespace

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/unit/pio_tests.h, tests/unit/test_common.c, tests/unit/test_darray.c
Just adding more comments based on continuing study of code and answers from Jim.
No code changes in this review.
Somehow we keep getting a lot of trailing whitespace. It might be my fault. I will see if I can sort that out and avoid it.
=> Adding comments

tests/unit/CMakeLists.txt
=> fixed CMake

src/clib/pio_getput_int.c, src/clib/pio_msg.c, tests/general/ncdf_get_put.F90.in, tests/general/util/pio_tutil.F90
This commit,
* Adds a test for pio_put/get_var 
* Fixes the code to get pio_put/get_var working for NULL start/count pointers
* Fixes code to get pio_put/get_var working for char strings
Fixes #204
=> Get pio_put/get_var to work for NULL start/count pointers

src/clib/pio_spmd.c, tests/unit/test_spmd.c
In the interests of keeping code changes separate from test changes, I would like to merge my current branch, and continue development of test_spmd on a new branch.
In this PR I added checking of return values for all MPI function calls in pio_spmd.c. (See #225). 
There is also some development of test_spmd. I am getting some confusing results, so I wanted to make sure that none of the MPI functions was returning errors.
=> Checking return values for MPI calls in pio_spmd.c (also continued development of test_spmd)

src/clib/pio_msg.c, src/clib/pioc.c
There are still some stragglers but this PR adds return code checking for most of our MPI function calls.
This is in support of #225.
=> Check return values from most MPI function calls

src/clib/pio_msg.c, src/clib/pio_nc4.c, src/clib/pioc_support.c, tests/unit/test_nc4.c
=> Revert "Added async handling of nc4 functions, plus testing"

tests/unit/test_nc4.c
This one line change is needed for the tests to pass cdash tonight...
=> fixed for running on > 4 tasks

src/clib/pio_msg.c, src/clib/pio_nc4.c, tests/unit/test_nc4.c
Fixes #106.
The special netCDF-4 optimization functions were not working or tested with async. Now they are.
This code was already approved and I attempted to merge it, but it got tangled up with something else, so I reverted. Now everything is sorted out and I am going to merge these changes again.
=> Async for nc4 functions, with testing

src/clib/pio.h, src/clib/pio_darray_int.c, src/clib/pio_spmd.c, src/clib/pioc.c
Fixes #246.
Also applied #234 to the affected functions.
=> Fix warnings in C code

src/clib/pio_file.c
Cleaned up documentation and whitespace issues. No code changes.
=> cleaned up documentation

src/clib/pio_internal.h, src/clib/pioc_support.c
Fixed a compiler warning generated by recent merge.
=> fixed compiler warning

src/clib/pioc_sc.c
Fixes #255.
Cleanup and documentation only - no code changes.
There are some ??? that could use comments...
=> whitespace cleanup

doc/source/base.txt, doc/source/contributing_code.txt
=> code review process changes based on github issue

src/clib/pio_file.c, tests/unit/test_nc4.c
=> Fix of problem in deletefile

examples/c/example2.c
Fixed warning in example2 compile. Fixes #269.
=> fixed warning in example

src/clib/pio_file.c, src/clib/pio_getput_int.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pioc.c
Part of #225.
I am working on #238 and the error handling is giving me trouble. So I want to get these changes in to make sure nothing funny is going on with the MPI return codes.
=> Proper handling of MPI return codes in several files

ctest/runcdash-nwsc-pgi.sh
Updates pgi, netcdf and pnetcdf versions for cdash testing on yellowstone
=> update pgi modules on yellowstone

src/clib/pio.h, src/clib/pioc_support.c, tests/unit/test_names.c
Working on the error code I noticed several problems with PIOc_strerror(). They are fixed in this PR. I would like to get this reviewed and merged to develop before continuing on the other error code issues.
Fixes #279.
=> fixed PIOc_strerror and added better tests for it

src/clib/pio.h, src/clib/pio_file.c, src/clib/pio_internal.h, src/clib/pioc_support.c
=> fixed problem with uninitialized file_desc_t pointer

ctest/runcdash-alcf-ibm.sh, ctest/runcdash-cgd-nag.sh, ctest/runcdash-nersc-cray.sh, ctest/runcdash-nersc-intel.sh, ctest/runcdash-nwsc-gnu.sh, ctest/runcdash-nwsc-intel-mpiserial.sh, ctest/runcdash-nwsc-intel.sh, ctest/runcdash-nwsc-pgi.sh, ctest/runcdash-nwscla-intel.sh
update cdash tests to explicitly get the develop branch
=> Update cdash tests

tests/unit/test_names.c
Fixes #289.
This may fix what is causing test_names to fail on some CDash platforms.
=> Ejh fix test names

src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_varm.c, src/clib/pioc_support.c
Trying again to merge these changes to develop.
=> Ejh check netcdf2

src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_varm.c, src/clib/pioc_support.c
=> Revert "Ejh check netcdf2"

ctest/runcdash-nwsc-intel-mpiserial.sh, tests/unit/test_names.c
Line to cd to src directory was missing.
=> Runcdash fix mpiserial

tests/unit/test_names.c
Thought this fix made it in last week, but it got lost in my git confusion.
So here it is again. ;-)
Fixes #304.
=> fixed test_names problem with lack of return code for check_strerror 

examples/c/CMakeLists.txt, src/clib/pio.h, src/clib/pio_file.c
Fixes #273.
Clean up if file_desc_t initialization with calloc.
=> cleaned up file_desc_t initialization with a calloc

src/clib/pio_internal.h, src/clib/pioc_support.c
Fixes #326.
Also fixes error handling in accordance with #225.
=> changes to calloc, fixed error handling in open funtion

doc/source/mach_walkthrough.txt, tests/unit/CMakeLists.txt, tests/unit/driver.F90
Fix #353.
Also updated documentation on build to match recent releases of libraries.
=> removed nc_set_log_level_2_, updated docs

src/clib/pio_rearrange.c
Fixes #212.
Part of #225.
I have added return code checking for two calles in pio_rearrange.c.
=> added return code checking

cmake/FindNetCDF.cmake, src/clib/CMakeLists.txt
Add a test to see if netcdf has logging enabled.   This sets  NetCDF_C_LOGGING_ENABLED
the variable is not yet used.
=> Add cmake check for nc logging

src/clib/pio_file.c, src/clib/pio_msg.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_iosystem2.c
Part of #225.
I want to get these changes in before I start modifying this code for other issues.
I will merge these changes into develop for testing.
=> Error handling cleanup

tests/general/CMakeLists.txt, tests/general/ncdf_inq.F90.in
Adding a test for some pio (variable, dim, att) inquire functions.
More tests are required for better coverage, but this is a
start.
=> Adding tests for pio inquire functions

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pioc.c
=> Ejh error handling 2

src/clib/pio_nc.c, src/clib/pioc_support.c
=> Ejh more return code checking

src/clib/pio_getput_int.c, src/clib/pio_nc.c, src/clib/pio_nc4.c
I got a little tangled up so merged my last PR without review approval (but it did pass all CDash tests). Take a look at it in the close PR list.
In this PR I continue fixing return codes. In our C library we must check ALL return codes from every function that returns an error code. (Otherwise, what kind of dopes will we look like when there is a bug, and some return code indicated a problem all along, but we just ignored it?)
Fixes #225.
I will merge this into develop for testing.
=> Ejh even more returns

src/clib/pio_getput_int.c
We need a test, but here is the fix.
I will merge with develop, then do a test tomorrow...
=> fixed nelems

src/clib/pio_getput_int.c, tests/cunit/test_pioc.c
Added a section to do a put and then a get.
But the get does not work. Not yet clear why so it is commented out while I work on it. But I want to merge at least the one put test I've added, to get the ball rolling.
This PR contains test code changes only. No library code is changed.
This is part of #379. Also part of #205.
=> started to add tests for put/get

src/clib/pio.h, src/clib/pioc.c, tests/cunit/test_async_3proc.c, tests/cunit/test_async_4proc.c, tests/cunit/test_async_simple.c, tests/cunit/test_darray.c, tests/cunit/test_intercomm2.c, tests/cunit/test_pioc.c
=> Changes to init async API

src/clib/pio_file.c, src/clib/pio_msg.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c
Fixes #349.
Fixes #348.
Fixes #238.
Contributes to #205.
This PR contains some fixes and turns on async testing for all the tests in test_pioc.c (many of those tests, until now, were only working for non-async cases.)
Now all the tests in test_pioc.c are run for both async and non-async cases.
=> Got tests to work with async

ctest/runcdash-alcf-ibm.sh, ctest/runcdash-cgd-nag.sh, ctest/runcdash-nersc-cray.sh, ctest/runcdash-nersc-intel.sh, ctest/runcdash-nwsc-gnu.sh, ctest/runcdash-nwsc-intel-mpiserial.sh, ctest/runcdash-nwsc-intel.sh, ctest/runcdash-nwsc-pgi.sh, ctest/runcdash-nwscla-intel.sh
the cdash tests were not updating to the latest code on origin.  This fixes the issue, but each cdash source location will need to be removed or manually updated for it to take effect.
=> cdash was not updating to latest develop

src/clib/pio.h, tests/cunit/test_pioc.c
More on #379.
Still plenty of work to be done, but here's some new tests.
I had to add some data types to pio.h.
=> more putget testing

src/clib/pio.h, tests/cunit/test_pioc.c
Some more test code.
Part of #379.
Only test code changes in this PR. (Plus moved prototypes around to group by var1/vara, etc.)
=> more tests for putget functions

tests/cunit/test_pioc.c
=> Ejh more tests

src/clib/pioc_sc.c, tests/cunit/test_spmd.c
Took a test from main() and made it into a test in test_spmd.c.
Fixes #256.
=> Recovered old test code from pioc_sc.c

src/clib/pio_get_nc.c, src/clib/pio_put_nc.c
Added docs for some functions.
Part of #105.
No code changes in this PR, just documentation.
I will merge with develop for testing.
=> added documentation

tests/cunit/test_pioc.c
Fixes #396.
I have merged to develop.
=> fixed leak in test

tests/cunit/test_pioc.c
More tests for putget functions.
Part of #379.
No library changes in this PR, just new test code.
I will merge with develop for cdash testing.
=> even more tests

src/clib/pio.h, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, tests/cunit/pio_tests.h, tests/cunit/test_common.c, tests/cunit/test_intercomm2.c, tests/cunit/test_pioc.c, tests/cunit/test_spmd.c
Changes to pio.h include moving functions around and adding a missing function prototype. Also fixed an incorrect return code in pio_putget_int.c.
Otherwise just test code in this PR.
Part of #379.
I will merge with develop for testing.
=> more tests for put/get functions

ctest/runcdash-nwscla-intel.sh
update pnetcdf module on laramie cdash test
already merged to develop (replaces laramie_update which branched from wrong location)
=> branch from master

src/clib/pioc.c
=> fixed memory leak

src/clib/pio.h, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c
=> added way to save decomp file

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_varm.c, src/clib/pioc.c, src/clib/pioc_support.c
=> made fix for checking compmaster and iomaster using MPI_ROOT

src/clib/pioc_sc.c
=> removed old, unneeded macro TESTCALCDECOMP

src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_async_simple.c, tests/cunit/test_common.c, tests/cunit/test_iosystem2_simple.c, tests/cunit/test_pioc.c
More tests, and a fix.
Fixes #439.
Fixes #444.
Work on #430.
Work on #433.
=> More tests, plus some fixes to PIOc_inq_var_chunksizes()

src/clib/pio_getput_int.c, src/clib/pio_put_nc.c
Fixes #418 (in addition to PR #419).
=>  Check compmaster using MPI_ROOT

src/clib/pio_rearrange.c
Fixes #437.
Has been merged into develop for testing.
=> use pio_err() for error handling

src/clib/pio_msg.c
=> removed unneeded function

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_put_nc.c, src/clib/pioc_sc.c, tests/cunit/test_iosystem2_simple.c, tests/cunit/test_spmd.c
Fixes #445.
Also fixed MPI_ROOT change that got lost in a merge.
=> test gcd_array()

src/clib/pio.h, tests/cunit/test_iosystem2_simple.c
=> Ejh test set size limit

tests/cunit/test_iosystem2_simple.c, tests/cunit/test_iosystem2_simple2.c
=> Free new MPI communicators created by MPI_Comm_split()

src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_rearrange.c, src/clib/pioc_support.c
=> changed internal iodesc metadata to use malloc instead of bget

src/clib/pio_msg.c, src/clib/pioc_support.c
=> Fix memory leaks for test_pioc

src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pio_spmd.c
Fixes #475.
Has been merged to develop for testing.
=> fixed unneeded consts in function prototypes

tests/cunit/test_iosystem2_simple.c, tests/cunit/test_pioc.c
Part of #441.
Only test code in this PR, no library code changes.
=> test for several untested functions

src/clib/pio_msg.c, src/clib/pio_nc4.c, tests/cunit/test_pioc.c
Added some more tests for nc4 functions. Fixed def_var_deflate which was not working with async.
Fixes #432.
Fixes #433.
=> More nc4 tests, fix for async operation of PIOc_def_var_deflate()

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_lists.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_rearrange.c, src/clib/pio_spmd.c, src/clib/pioc_sc.c, src/clib/pioc_support.c, tests/cunit/test_async_simple.c, tests/cunit/test_intercomm2.c, tests/cunit/test_pioc.c, tests/cunit/test_spmd.c
Fixes #488.
Fixes #428.
While cleaning up warnings found and fixed a problem with PIOc_sync() in async cases.
Also added a test for PIOc_inq_atttype().
=> warnings and some more testing

tests/cunit/test_spmd.c
=> filled in missing test case

src/clib/pio.h, src/clib/pioc.c, tests/cunit/test_iosystem2_simple.c
=> removed duplicate function PIOc_get_iorank()

tests/unit/driver.F90
=> Finalize GPTL in the Fortran unit test driver

examples/c/example1.c, src/clib/pioc.c, tests/cunit/test_async_3proc.c, tests/cunit/test_async_4proc.c, tests/cunit/test_common.c, tests/cunit/test_iosystem2_simple2.c, tests/cunit/test_iosystem3.c, tests/cunit/test_pioc_putget.c, tests/cunit/test_shared.c, tests/cunit/test_spmd.c
Part of #494.
Has been merged to develop for testing.
=> fixed warnings

examples/c/examplePio.c, src/clib/pio_rearrange.c
=> used malloc

src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_msg.c, src/clib/pio_nc.c, tests/cunit/test_iosystem3.c, tests/cunit/test_pioc.c
=> Type conversion for attributes

tests/cunit/test_pioc_putget.c
Fixes #500.
New tests only, no changes to library code in this PR.
=> more tests for att conversions

src/clib/pio_msg.c
Fixes #514.
Fixes #512.
Some minor fixes for pio_msg.c.
=> fixed issues in pio_msg.c

src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/CMakeLists.txt, tests/cunit/pio_tests.h
Part of #417.
Starting testing reading/writing decomp files.
=> decomp tests

src/clib/pioc.c, src/clib/pioc_support.c, src/flib/pio.F90, src/flib/pio_types.F90, src/flib/piolib_mod.F90, tests/unit/driver.F90
=> changes to fix error handling in fortran test

tests/cunit/test_pioc_putget.c
Test was failing for classic only builds due to bug in test.
No library changes in this PR, just tests.
Fixes #523.
=> fixed test for classic-only builds

tests/cunit/test_pioc.c
Fixes #517.
Just extra test code in this PR, no library changes.
=> added tests for bad parameters

tests/cunit/test_decomps.c
=> Update new case test_decomps

src/clib/pioc.c
=> Free the MPI Info object

src/clib/pio.h, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_decomps.c, tests/cunit/test_pioc_putget.c
=> Add tests, and also fix checking of parameters in InitDecomp and InitDecomp_bc()

tests/cunit/test_intercomm2.c
Fixes #536.
No library changes in the PR, just tests.
=> turned on pnetcdf testing

src/clib/pio_msg.c, tests/cunit/test_pioc_putget.c
Fixes #527.
Fixes #425.
Test for writing arrays of text, with a fix to make it work.
=> fixed text reads/writes, added tests

src/clib/pio_nc.c, tests/cunit/test_pioc_putget.c
=> got _long() att functions working, tested

tests/general/ncdf_get_put.F90.in
Added a new Fortran test as part of #498.
=> Update ncdf_get_put to test more combinations of start/count

src/clib/pio_nc.c
Fixes #552.
Will merge it to develop for testing.
=> Fix test_pioc failure

src/clib/pio.h, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_put_nc.c, tests/cunit/test_pioc_putget.c
Fixes #105.
Contributes to #205.
Fixes #399.
=> Convert typeless get/put calls to match netCDF API, add tests

tests/cunit/CMakeLists.txt
=> Fix cunit test timeout issue on Valgrind builds

src/clib/pio_getput_int.c
Fixes #564.
Will merge to develop for testing (passed in local build).
=> Fix some issues in pio_getput_int.c

tests/cunit/test_pioc.c, tests/cunit/test_pioc_putget.c
=> Eliminate invalid characters from the test log

src/clib/pio_getput_int.c, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, tests/cunit/test_pioc.c
Fixes #570.
Fixes #434.
I have merged to develop.
=> Testing and async for PIOc_inq_var_fill() and PIOc_def_var_fill()

tests/cunit/test_spmd.c
Just new tests in this PR, no library code changes.
Fixes #575.
Part of #205.
=> added some tests for incorrect input for some list functions

tests/cunit/test_pioc.c
Fixes #588.
Part of #205.
Test code changes only - no library changes.
I will merge with develop.
=> more tests

src/clib/pio_file.c, tests/cunit/test_iosystem2_simple.c
=> more tests, took out evil log statement

src/clib/pioc_support.c
Doc fix only.
Fixes #594.
I have merged to develop.
=> fixed docs

src/clib/pio_rearrange.c, src/clib/pioc_support.c
=> fixed piodies

tests/cunit/test_pioc.c
Fixes #586.
Part of #205.
No library changes, only added a test.
=> added test

tests/cunit/test_pioc.c
=> Fixing memory leaks in test_pioc

tests/cunit/test_pioc_more.c
Added some tests for pnetcdf and fill values. Only test code changes in this PR.
Fill values still not working for pnetcdf for text and byte. Investigating that.
But now testing all the rest of the types.
Part of #580, part of #205.
=> now testing fill for pnetcdf

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pioc_support.c, tests/cunit/test_spmd.c
Part of #593, part of #591, part of #205.
Had to make these functions non-static so they could be tested.
Testing of internal functions actually found a bug, so it is worthwhile. Please add tests for all new functions, especially internal functions.
More tests coming for these functions. While doing this noticed issue #618. We'll merge these tests so far, then I will hit tests again after 618.
=> added tests for some functions

src/clib/pioc.c, tests/cunit/test_pioc.c
Fixes #585. Part of #441. Part of #205.
=> added tests

src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c, tests/cunit/test_pioc_more.c
=> initdecomp and freedecomp now work with async

CMakeLists.txt
=> removed unused CMake option

src/clib/pio.h, tests/cunit/test_pioc.c
Part of #417. Part of #205.
Only test code changes in this PR.
=> test for saving decomp file with async.

tests/cunit/test_spmd.c
Fixes #629.
Only test code changes.
Thanks to @dqwu for pointing this out.
=> fixed leak

src/clib/pio_file.c
Fixes #624.
See issue for discussion.
=> fixed preprocessor problem in deletefile

CTestScript.cmake, ctest/CTestEnvironment-anlworkstation.cmake, ctest/runcdash-anlworkstation.sh, ctest/runctest-anlworkstation.sh
=> Add CTest scripts for ANL workstations

tests/cunit/test_iosystem2_simple.c
=> Update test of bad IO types in test_iosystem2_simple

tests/cunit/test_pioc.c
=> fixed test to use MPI consts instead of 100 and 10000

src/clib/bget.c
=> fixed warning

tests/cunit/test_spmd.c
Fixes #636. Part of #205.
Generated issues #645 and #646, but we can merge these working tests, which test the actual functionality of these functions. If we find that needs to change, the tests can change with it.
=> added tests for ceil2() and pair() function in pio_spmd.c

tests/cunit/test_pioc_fill.c
Fixes #652.
Fixes #580.
Turn on some more of the fill value tests. Everything seems to be working fine. ;-)
No library changes, just test code in this PR.
=> Fill value tests

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, tests/cunit/CMakeLists.txt, tests/cunit/test_darray.c, tests/cunit/test_pioc_darray.c
I have added a new test program test_darray.c. It is still not doing what I expect (it currently writes all zeros instead of the sample data I expect it to). (But the test does pass - it won't break the build.)
I will continue working on this test in future PRs.
This PR also includes some whitespace cleanup, documentation additions, and logging statements for some of the darray functions, as I get this functionality figured out, tested, and then make it support async.
Part of #83, #89, #205, #473, #543, #664, #665.
I will wait for comments before merging to develop.
=> added darray test, added logging and documentation to some darray functions

tests/general/pio_decomp_tests.F90.in, tests/general/pio_decomp_tests_1d.F90.in
Adding more 1d fortran tests,
* More combinations that force data rearrangement during read and write tested
* Testing reusing iodescs across reads (and reads+writes)
=> Adding more 1d Fortran tests

src/clib/pio_darray_int.c
=> removed unneeded ncid variable

tests/cunit/pio_tests.h, tests/cunit/test_decomps.c, tests/cunit/test_intercomm2.c, tests/cunit/test_iosystem2.c, tests/cunit/test_iosystem2_simple.c, tests/cunit/test_iosystem3.c, tests/cunit/test_pioc.c, tests/cunit/test_pioc_putget.c
=> used named const instead of 42

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pioc_support.c, tests/cunit/test_pioc.c, tests/cunit/test_spmd.c
=> added basetype to PIOc_read_nc_decomp()

src/clib/pio_darray_int.c, src/clib/pioc_support.c, tests/cunit/CMakeLists.txt, tests/cunit/test_darray.c, tests/cunit/test_darray_3d.c
Added a bunch of test code.
Added documentation and some log statements to darray code.
Fixes #697.
Fixes #417.
Part of #664.
Part of #205.
=> Tests for darrays and decompositions

src/clib/pio_getput_int.c
=> use PNET_READ_AND_BCAST always

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pioc_support.c, tests/cunit/test_darray.c, tests/cunit/test_darray_3d.c, tests/cunit/test_pioc.c
Fixes #696. See issue for discussion.
=> changed from fortran to C datatype (MPI_INTEGER to MPI_INT)

tests/cunit/test_darray.c
Fixes #701.
Only test code in this PR, no library changes.
=> darray tests for bad input parameters

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c
See #695 for full discussion.
Fixes #695.
Fixes #700.
=> Took out unused struct member and function parameter gsize.

doc/source/mach_walkthrough.txt, src/clib/pioc_support.c, tests/cunit/test_pioc.c
Fixes #706.
Fixes #694.
Change the version attribute in netCDF decomp files, also fixed a bug writing netCDF decomp files.
=> fixed gather bug, change decomp version attribute

tests/cunit/pio_tests.h, tests/cunit/test_common.c, tests/cunit/test_darray.c, tests/cunit/test_decomps.c
Just moved some test code.
Fixes #705.
=> moved test code

src/clib/pio_darray_int.c
=> Add documentation, remove unused variable

tests/cunit/test_darray_3d.c
Added test code only, no library code changes.
Part of #664.
Part of #205.
=> added 4D darray test

src/clib/pio_darray.c, src/clib/pio_darray_int.c
=> removed incorrect MPI fortran types

tests/cunit/test_darray_3d.c
Just more test code, no changes to the library in this PR.
Part of #664. Part of #205.
=> Added a second record to the test data in test_darray_3d.c

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_multivar.c
Test has turned up a potential problem in pnetcdf fill values (#729).
This test will continue to develop in future PRs. It passes now.
Part of #729, part of #726, part of #205.
=> added test_darray_multivar.c

src/clib/pio_darray_int.c, tests/cunit/test_pioc_fill.c
Fixes #732.
Fixes #735.
Added some comments to the code, and some new fill value tests.
=> More tests for fill values

src/clib/pio_darray_int.c, tests/general/CMakeLists.txt, tests/general/pio_rearr.F90.in
Fixing NetCDF read failures across rearrangers. Also adding some
tests for rearrangers.
Fixes #737
=> Fix netcdf read error across rearrangers

src/clib/pio_darray.c, tests/cunit/CMakeLists.txt, tests/cunit/test_darray_1d.c
Added test_darray_1d.c for tests that can be run on a 1D data file. ;-)
Added tests for fill values when decomposition leaves values out.
Part of #89.
Part of #205.
Fixes #664.
=> Another darray test, this one 1D for extra simplicity

src/clib/pio_darray.c, src/clib/pio_darray_int.c
=> took out printfs, called buffer logging only when logging is enabled

src/clib/pio_getput_int.c, src/clib/pio_nc.c, tests/cunit/test_pioc.c
Noticed PIOc_get_att() was not being tested under async. Added it to testing and found and fixed a bug.
Fixes #659.
Part of #205.
=> added test, fixed async bug

src/clib/pio_darray.c, tests/cunit/test_darray_1d.c
Added tests to test_darray_1d.c.
No library changes in this PR, just test code.
This test led to issue #743. The test has been modified to avoid that test case pending solving that issue.
Fixes #741.
Fixes #727.
Fixes #749.
Part of #205.
=> test development

tests/cunit/test_darray_3d.c
Converted test_darray_3d.c to test both rearrangers.
Fixes #745.
=> added box rearranger to test

src/clib/pio_darray.c
Documentation changes only.
I will merge into develop.
Fixes #692.
=> documentation improvements

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_darray_1d.c
Can you try this before I merge to develop and make sure that it works for you.
=> fix memory issue in this test

src/clib/pio_darray.c, tests/cunit/test_darray_1d.c
More darray tests, this time without providing fill values.
Fixes #756.
Part of #205.
Part of #83.
=> took out silly check for vdesc; added tests for darray with no fillvalue

src/clib/pio_nc.c, tests/cunit/test_darray_multivar.c
Added more testing in test_darray_multivar.c.
Still cannot figure out why pnetCDF files don't give me fill values in the empty vars in this test. There's a ticket open for that. (#729).
Fixed some docs in the code, but no code changes in this PR, only test code.
I will merge with develop for testing.
Part of #726.
Part of #758.
Part of #205.
Part of #83.
=> more darray tests for fill values with multiple variables

tests/cunit/test_darray.c, tests/cunit/test_darray_3d.c
More testing for darrays.
Only test code changes in this PR - no library changes.
Fixes #758.
Fixes #756.
Part of #205.
Part of #83.
=> Even more darray tests

src/clib/pio_spmd.c, tests/general/CMakeLists.txt, tests/general/pio_rearr_opts.F90.in, tests/general/pio_rearr_opts2.F90.in
This PR includes,
* Fixes to the fortran pio rearranger tests to use all the rearranger options
* More Fortran tests for testing rearranger options
* Fixes to the pio flow control code
* Minor doc fixes and logging
Fixes #637 
Fixes #645
=> Fix issues in flow control code and associated tests

src/clib/pio.h, src/clib/pio_darray.c
=> changed param names

tests/cunit/test_pioc.c, tests/cunit/test_spmd.c
Just test changes in this PR.
Better testing for invalid parameters for some netcdf-4 only functions.
Part of #205.
Fixes #769.
Fixes #766.
=> checking invalid parameters

tests/cunit/test_darray.c
More tests.
Fixes #765.
Part of #205.
=> more tests for PIOc_write_darray_multi()

src/clib/CMakeLists.txt
=> included library in cmake file

src/clib/pio_darray.c
Fixes #611.
Further simplification of this code coming with #713.
Also fixes #784.
=> simplified code

tests/cunit/test_iosystem2_simple.c, tests/cunit/test_pioc.c
=> Added some tests to fill in coverage

src/clib/pio_internal.h, src/clib/pioc_sc.c, tests/cunit/test_spmd.c
Some simple C tests for function computestartandcount().
No code changes, but I did add comments to the code.
Please add review comments where I have ??? and I will add it to the code.
Fixes #792. Part of #205.
=> added tests, comments to function computestartandcount()

src/clib/pio_internal.h, src/clib/pioc_sc.c, tests/cunit/test_spmd.c
Some minor changes to pioc_sc.c. Added some pioasserts, added some comments.
Fixes #802.
Fixes #801.
Fixes #798.
Fixes #799.
Fixes #800.
=> some minor changes in pioc_sc.c

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_1d.c, tests/cunit/test_darray_uneven.c
Yet another test. This one is for uneven distributions of data. It will contine to expand in future PRs.
No library code changes in this PR, just new test test_darray_uneven.c.
Part of #728.
Part of #89.
=> Added new C test: test_darray_uneven.c

tests/cunit/test_intercomm2.c, tests/cunit/test_pioc_fill.c
Based on coverage report.
Fixes #820.
Fixes #819.
Part of #205.
=> Added 2 small extra tests

src/clib/pio_darray.c
Minor cleanup of code getting to end of wmb list.
Fixes #829.
=> cleanup getting to end of wmb list

src/clib/pio_darray.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c
Now using pio_err() everywhere. See ticket for more discussion.
Fixes #435.
=> removed piomemerror() function

tests/cunit/test_async_simple.c
Added test case for PIOc_init_async().
Fixes #508.
Part of #205.
=> testing io_proc_list and proc_list

doc/source/contributing_code.txt
Fixes #835.
Documentation change only.
Has been merged into develop.
=> fixed doc mistake

tests/cunit/test_spmd.c
=> added test with bad input

tests/cunit/test_spmd.c
Test code only in this PR.
C tests for internal function cmp_rearr_opts().
Fixes #839.
Part of #205.
Part of #837.
=> added tests for cmp_rearr_opts()

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_1d.c, tests/cunit/test_darray_multi.c
No library changes, only test changes in this PR.
Fixes #752.
Part of #205.
Part of #83.
=> Added test for PIOc_write_darray_multi() with more than 1 variable

tests/cunit/test_darray_multivar.c
=> Testing more types for darray in test_darray_multivar.c

src/clib/pio_darray.c
Use a pioassert to assure that the rearranger is valid.
Fixes #841.
=> used pioassert in PIOc_write_darray_multi()

tests/general/ncdf_get_put.F90.in
Adding two tests that puts/gets slices of arrays
* A test that puts/gets a 1d array slice of a 2d var
* A test that puts time slices of 2d/3d/4d vars and reads it
=> Adding some fortran tests that puts/gets slices of arrays

cmake/LibCheck.cmake
I don't understand cmake well enough to puzzle this out, but sometimes we get an error that
check_function_exists doesn't exist.   After adding this include I have not been able to reproduce that error.     I will merge to develop
=> need this to use check_function_exists

src/clib/pio_internal.h, src/clib/pioc_support.c
More arg checking when user sets rearranger options.
Fixes #618
Fixes #837
=> More arg checking when user sets rearranger opts

src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/CMakeLists.txt, tests/cunit/test_darray_1d.c, tests/cunit/test_rearr.c, tests/cunit/test_spmd.c
I created a new test, test_rearr.c, for rearranger tests. I moved some existing rearranger tests out of test_spmd.c into test_rearr, And I added some new tests to test_rearr.c.
Also documentation improvements, and logging statements to help me figure out what is going on.
Part of #89.
Part of #205.
Part of #857.
=> added new test program test_rearr with some tests for internal functions in pio_rearrange.c

tests/cunit/test_darray_uneven.c
Added another test case.
Part of #728.
Part of #205.
=> added test for unevenly distributed decomp

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c
Changes to documentation only in this PR. No code changes.
Fixes #832.
Fixes #753.
=> added some comments to code

src/clib/bget.c, src/clib/pio_darray_int.c, tests/cunit/test_pioc.c
=> fixed if/ifdef issue, stopped some async tests that fail for bget

src/clib/pio_rearrange.c
Added some asserts, added some documentation.
Part of #869.
=> some pioasserts

src/clib/pio_darray_int.c
Fixes #883.
I will merge it to develop for testing.
=> Fix memory leaks related to CN_bpool

src/clib/pioc_sc.c, tests/cunit/test_spmd.c
Added test and some documentation for this function. Still not clear what is going on - any comments where ??? are would be most appreciated.
Fixes #893.
=> added test for GDCblocksize

src/clib/pio_rearrange.c
=> Added more asserts, now checking return value of pio_swapm() calls

src/clib/pio.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
=> Added tests for function define_iodesc_datatypes(), also comments

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, src/clib/pioc_sc.c, tests/cunit/test_spmd.c, tests/general/util/pio_tutil.F90
Tested with and without PIO_USE_MALLOC
=> Memleak fix

src/clib/pioc_sc.c
Comments only, no code changes in this PR.
FIxes #900.
=> added Jim's comments to some code pioc_sc.c

src/clib/pioc_sc.c, src/clib/pioc_support.c
Some code that was causing a problem for openmpi turns out to not be used anyway, so I removed it.
Part of #898.
Part of #897.
=> removed unneeded code

tests/cunit/test_pioc.c
=> turned test back on for async

src/clib/pioc_support.c
=> fixed warning C warning in pioc_support.c

src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
Added some return code checking.
Fixes #914.
=> Return code checking when allocating region

src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
=> io region use calloc

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pio_rearrange.c, tests/cunit/test_rearr.c
Added test and some logging for compute_counts() function in pio_rearrange.c.
Part of #205.
Part of #857.
This test will get further development in future PRs. There are plenty of '???' in the compute_counts() function that could use comments.
=> added test, logging

src/clib/pio_rearrange.c
Fixes #921.
See issue for explanation.
=> compute_counts() never called for subset rearranger

src/clib/pio_rearrange.c, tests/cunit/test_rearr.c
Fixes #923.
Thanks @dqwu for spotting this one.
=> fixed memory problem in test_rearr.c

ctest/runcdash-nwsc-intel-mpiserial.sh
Addresses #925 
merged to develop
=> Jpe update mpi serial path

src/clib/pio_rearrange.c
=> using old function names for mpiserial

src/clib/pio_rearrange.c, src/clib/pioc.c, tests/cunit/test_darray_1d.c, tests/cunit/test_rearr.c
Also logging and comments in the code files.
Part of #205.
Part of #89.
Part of #857.
=> C test for box_rearrange_create()

src/clib/pio_darray.c, src/clib/pio_spmd.c
=> error handling and logging

src/clib/pio_nc.c
Fixes #930.
Also parameter no_fill was misnamed fill_mode.
=> Fix problem with PIOc_inq_var_fill()

src/clib/pio_darray.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, tests/cunit/test_rearr.c
Added test for default_subset_partition().
Also starting testing for rearrange_comp2io().
Part of #857.
Part of #205.
Fixes #937.
=> added test for default_subset_partition()

src/clib/pio.h, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
Added test code for the rearrange_comp2io() function.
Also added some logging statements and comments as I understand this code.
Also shortened some field names so that using them does not result in such long names.
Part of #857.
Part of #205.
Part of #89.
=> more test code, more logging statements, shortened some field names

examples/c/CMakeLists.txt, examples/c/darray_no_async.c, src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_nc.c, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_sc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c
Also added new example.
Fixes #942.
=> Documentation, removed some duplicate code

examples/c/CMakeLists.txt, examples/c/darray_async.c, examples/c/darray_no_async.c, src/clib/pio_rearrange.c, src/clib/pioc.c, tests/cunit/test_async_4proc.c
Fixes #944.
I will merge to develp for testing.
=> Comments, code cleanup

examples/c/CMakeLists.txt, examples/c/darray_async.c, src/clib/pio.h, src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc.c, tests/cunit/test_rearr.c
Added more comments.
Fixes #858.
=> More comments in the code as I figure out async 

tests/cunit/test_rearr.c
Only test code changes in this PR.
Fixes #949.
=> used calloc for test code cleanup

src/clib/pio.h, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_getput_int.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_rearrange.c, src/clib/pio_varm.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
Only the name has changed.
Fixes #948.
=> changed name of field async_interface

CMakeLists.txt, src/clib/config.h.in, src/clib/pio_rearrange.c
=> now put MPI_Offset size in config.h

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_rearr.c
More tests, more comments.
Part of #857.
Part of #205.
Part of #89.
=> More tests and comments

src/clib/pio_internal.h, src/clib/pio_rearrange.c
=> More comments, more asserts

src/clib/pio_rearrange.c, tests/cunit/test_rearr.c
=> fixed memory problem in test, tightened asserts, added comments

tests/cunit/test_rearr.c
=> fixed memory problem in test

CMakeLists.txt, src/clib/CMakeLists.txt
Have a look and see if this is better than hardcoding 8.   I'll wait for review before merging to develop.
=> move mpi discovery to top level

src/clib/pio.h, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_msg.c, tests/cunit/test_pioc.c
Scalar var reads still not working for pnetcdf. I will track that under a separate issue.
Fixes #966.
Fixes #961.
=> changes to support scalar vars

tests/cunit/pio_tests.h, tests/cunit/test_rearr.c
More test code. No library changes.
Fixes #970.
Part of #968.
Part of #205.
=> more tests for scalar vars

src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_msg.c, src/clib/pio_put_nc.c, tests/cunit/test_intercomm2.c, tests/cunit/test_pioc.c
=> added PIOc_put_var_tc()

src/clib/pio_getput_int.c, tests/cunit/test_pioc.c
For pnetcdf we need to handle writing scalars differently from writing arrays. I have added the code to accomplish this.
Fixes #968.
=> pnetcdf scalars now working

tests/cunit/test_pioc.c
Fixes #985.
Fix a dumb mistake in test code.
This has been merged to develop for testing.
=> fixed pnetcdf build issue

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c
Only changed the name.
Fixes #831.
=> changed member name validvar to num_arrays

tests/general/ncdf_get_put.F90.in
Added a new Fortran test as part of #961.
=> Update ncdf_get_put to test scalar variables

src/clib/pio_rearrange.c, src/clib/pioc.c, tests/cunit/test_pioc.c
This change has no effect on non-async cases.
Part of #89.
Part of #981.
=> Change to compute counts to support async

src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, tests/cunit/test_pioc.c, tests/cunit/test_shared.c
Got init decomp working for async with box rearranger.
Also added some comments.
These changes have no effect on non-async operation.
Fixes #981.
Part of #89.
=> Getting init decomp working with box rearranger for async cases

CTestScript.cmake, ctest/runcdash-nwscla-intel.sh, ctest/runctest-nwscla.sh
Fix issues with cdash test on cheyenne
already merged to develop
=> Cheyenne cdash fix

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_rearrange.c
=> make use of iodesc->basetype_size field

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_internal.h, src/clib/pio_msg.c, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/CMakeLists.txt, tests/cunit/test_darray_async.c, tests/cunit/test_darray_async_simple.c
With this PR, async darray writes will work with a variable that includes the unlimited dimension.
Part of #89.
Part of #1005.
Part of #388.
=> Async darray write working with var using unlimited dimension

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_darray_1d.c, tests/cunit/test_darray_3d.c, tests/cunit/test_decomp_uneven.c, tests/cunit/test_decomps.c, tests/cunit/test_pioc.c, tests/cunit/test_rearr.c
Fixes #690.
No other code changes, just renamed basetype to mpitype.
=> change name from basetype to mpitype

tests/cunit/test_darray_async.c
Expanded a test.
No library changes in the PR, just test code.
Fixes #1005.
Part of #89.
Part of #388.
=> darray write tests with async mixing record and non-record var

src/clib/pio_darray_int.c
These are (almost) the same changes that I had up for PR yesterday.
Some changes to write_darray_multi_par() to match the changes to write_darray_multi_serial() in support of async.
Part of #1030.
Part of #89.
=> changes to write_darray_multi_par() in support of async code

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_async_many.c
This test will be further developed in future PRs. Only test code in this PR, no library code changes.
Part of #1027.
=> Adding darray async test

tests/cunit/test_darray_async_many.c
Only additional test code in this PR. No library code changes.
This is further development of test_async_darray_many.c. This test now uses 5 different decompositions, to write data of all types, record and non-record. 
Fixes #1027.
Fixes #1025.
=> test development for darray async code

src/clib/pio_darray_int.c, tests/cunit/test_darray_async.c, tests/cunit/test_darray_async_many.c, tests/cunit/test_darray_async_simple.c
Actually, it worked with no code changes. ;-)
Next comes pnetcdf, but I doubt I will be so lucky.
Part of #1030.
Part of #388.
Part of #89.
=> Turning on testing for async darrays with PIO_IOTYPE_NETCDF4P

src/clib/pio_darray_int.c, src/clib/pioc_support.c, tests/general/pio_decomp_frame_tests.F90.in
=> Updating number of PnetCDF requests correctly

src/clib/pio_darray.c
Fixes #940.
As suggested by Jim, we need to try the malloc first and call flush if the malloc fails and then try the malloc again.
=> Special handling for PIO_USE_MALLOC=ON to flush buffer

src/flib/piolib_mod.F90
Fixes #1048 
It has been merged to develop for testing (will test the fix on Mira/Cetus as well).
=> Fixing build errors for XL Fortran compiler

src/clib/pio_lists.c
=> took abs out of list function

src/clib/pio.h, src/clib/pio_file.c, src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_msg.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_common.c, tests/cunit/test_darray_multivar.c, tests/cunit/test_pioc.c, tests/cunit/test_pioc_putget.c
Continuing work on changes to support changes to the varlist.
Fixes #1060.
Part of #1051.
Part of #1052.
Part of #544.
=> added PIOc_openfile2()

tests/cunit/CMakeLists.txt, tests/general/CMakeLists.txt
=> increased timeouts

src/clib/pio_lists.c, src/clib/pioc_support.c
More code for varlists.
Part of #1051.
Part of #1052.
Part of #544.
=> adding code to inquire about variable dimensions on open

doc/source/mach_walkthrough.txt
Documentation update with new versions of HDF5 and netCDF.
Fixes #1068.
=> updated build instructions

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_getput_int.c, src/clib/pio_msg.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_rearrange.c, src/clib/pio_spmd.c, src/clib/pioc.c
Rest of #1055.
Got tired of doing these piecemeal.
If you see any incorrect or incomplete author tags, now or at any future time, let me know so that they can be as accurate as possible. Probably I am missing Jayesh in a few places, but I don't remember which functions in pio_rearranger.c he worked on.
merged into develop for testing.
=> documentation changes only, mostly authortags

src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pioc_support.c
moved file level iobuf to file_desc_t from var_desc_t
Fixes #1074.
Part of #544.
=> moved file level iobuf to file_desc_t from var_desc_t

doc/source/mach_walkthrough.txt, src/clib/pioc_support.c
=> fixed problem with netcdf classic only build

tests/cunit/test_darray_multivar.c
=> now check all vars

src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_nc.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c
Fixes #1080.
Part of #1052.
Fixing a problem with varidp in PIOc_def_var, and moving towards linked list for var_desc_t.
=> Fixing problem with varidp in PIOc_def_var, advancing towards using linked list of var_desc_t

src/clib/pio_darray_int.c
=> changed pointer arithmetic

src/clib/pio.h, src/clib/pio_darray.c
In this PR I remove some unneeded fields in the var_desc_t struct.
Fixes #1051.
=> removed unneeded fields

src/clib/dtypes.h
=> deleted unused file dtypes.h

src/clib/pio_darray.c, src/clib/pio_spmd.c, tests/cunit/test_darray.c, tests/cunit/test_darray_multi.c, tests/cunit/test_iosystem2_simple.c
=> Some additional testing

CMakeLists.txt, src/clib/pioc_support.c, tests/cunit/test_darray_async.c, tests/cunit/test_decomps.c
=> More testing

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_async_many.c
Turned on test that wasn't running (thanks @dqwu).
Fixes #1108.
Fixes #1100.
=> got test working with new darray type checking

src/clib/pio.h
=> changed attribute

src/clib/pio_file.c
=> added redurn code checking

tests/cunit/test_pioc.c, tests/cunit/test_pioc_fill.c
Test code changes only in this PR.
Fixes #1118.
=> changed returns to use ERR() macro

src/clib/pioc_support.c
=> took out incorrect mode flag setting

tests/cunit/test_darray_async.c
Test code only in the PR.
Fixes #1098.
=> Added async test for PIOc_write_darray multi()

src/clib/pioc.c, tests/cunit/test_pioc.c
=> removed rec_var check from setframe/advanceframe

src/clib/pio_darray.c
=> clean up write_darray()

tests/general/pio_decomp_frame_tests.F90.in
This test case is used for issues #1128 and #1136.
I will merge it to develop branch for testing.
Note: This test can pass before PR #1084 was merged. Before issue #1136 is fixed, it should fail as expected.
=> Add a new Fortran test for limited time dimension

examples/c/CMakeLists.txt, src/clib/Makefile.am, src/clib/pio_internal.h, src/clib/pio_rearrange.c, tests/cunit/test_darray.c, tests/cunit/test_darray_1d.c, tests/cunit/test_darray_3d.c, tests/cunit/test_darray_multi.c, tests/cunit/test_darray_multivar.c, tests/cunit/test_darray_multivar2.c, tests/cunit/test_darray_multivar3.c, tests/cunit/test_rearr.c, tests/cunit/test_spmd.c
Working to get tests working with autotools.
Part of #1135.
=> More work on autotools build

tests/cunit/test_intercomm2.c
=> changes to support new autotools build

src/clib/pio_msg.c
Fixes #1142.
Fixed the error handling in pio_msg.c.
=> fixed error handling in pio_msg.c

tests/cunit/test_iosystem2.c
=> cleaned up test output

configure.ac, tests/cunit/test_darray_2sync.c
Also sorted out a test issue.
Part of #1135.
=> added detection of netCDF-4 parallel in autotools build

configure.ac, doc/source/mach_walkthrough.txt
Now configure finds size of MPI_Offset.
Part of #1135.
No effect on CMake builds.
=> Further development of autotools build

src/clib/Makefile.am, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_spmd.c
In this PR I added some documentation, got make distcheck working, and fixed run_tests.sh so that it returns a non-zero code if a test fails.
Fixes #1135.
=> Finished first take at autotools build

src/clib/pioc_support.c, tests/cunit/Makefile.am
=> changed log file extension to log

tests/cunit/CMakeLists.txt, tests/cunit/test_darray_2sync.c
=> fixed test

tests/cunit/test_darray_2sync.c
=> expanded test in preparation for fill value work

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_nc.c, src/clib/pioc_support.c, tests/cunit/test_spmd.c
Part of #1163.
Part of #83.
Added pio_type_size and other fields to var_desc_t.
=> added pio_type_size and other fields to var_desc_t

src/clib/pio.h, src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_nc.c, src/clib/pioc_support.c, tests/cunit/test_spmd.c
Fixes #1163.
Part of #83.
Added some more fields to var_desc. 
=> added some fields to var_desc

doc/source/Decomp.txt
=> add a missing element

tests/cunit/CMakeLists.txt, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_async_mpi.c
Part of #1134.
Test with just MPI code to establish communicators between one IO and 2 computation components.
=> added test program

src/clib/pio_darray_int.c
Fixes #1173 
The new Fortran test in PR #1174 should pass with this fix.
=> Adding data conversion support for NetCDF type

tests/general/ncdf_simple_tests.F90.in
This Fortran test can reproduce the issue described in #1173.
I will merge it to develop branch for testing, which is expected to pass for PnetCDF type and fail for NetCDF type.
=> A new Fortran test to check whether pio_read_darray supports data conversion

doc/source/mach_walkthrough.txt, src/clib/pioc.c, tests/cunit/CMakeLists.txt, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_async_multicomp.c
Part of #1134.
Adding another test, plus some changes to support multiple computation components with async.
=> Test for multiple computational components

src/clib/pio_msg.c, src/clib/pioc.c, tests/cunit/test_async_mpi.c, tests/cunit/test_async_multicomp.c
Part of #1134.
Test development. More to come on these tests, but this code passes.
=> More test development

src/clib/pio.h, src/clib/pioc.c
=> removed structure fields that werent needed

src/clib/pio_internal.h, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_spmd.c
=> Moved some code form PIOc_init_async() to separate function

src/clib/pioc.c
=> fixed iocomm

tests/cunit/test_async_multicomp.c
=> commented out failing test code

tests/cunit/test_pioc.c
Part of #1134.
Added test. No library changes in this PR.
=> Added test for empty files

src/clib/pio_lists.c, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pioc.c, tests/cunit/test_async_multicomp.c
Part of #1134.
Now my two computation components are inited and finalized OK, and one of them creates a test file.
More test development to come.
=> Some changes to get multiple computation components working

src/clib/pioc_support.c, tests/cunit/test_async_multicomp.c, tests/cunit/test_iosystem3.c
Fixes #1190.
Fixes #1134.
Fixed problem with ncid on multiple computation components. Turned on rest of test for multiple computation components.
=> Fix for ncid problems with multiple computation components

tests/cunit/CMakeLists.txt, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_async_mpi.c, tests/cunit/test_async_multi2.c, tests/cunit/test_async_multicomp.c
Part of #1194.
Added test_async_multi2.c. In this PR, it now checks attributes of all possible types.
More to come for this test, but I would like to get these changes merged.
=> Adding test code for multiple computation components

tests/cunit/test_rearr.c
Fixes #1197 
I will merge this fix to the develop branch for testing.
=> Fix a random failure (on MPI_Type_free) for test_rearr 

src/clib/pio_file.c, src/clib/pio_lists.c, tests/cunit/test_spmd.c
=> Fixing some list code

src/clib/pio_internal.h
=> fixed up documentation

CMakeLists.txt, configure.ac, doc/source/base.txt
Getting ready for release. Part of #1217.
I have also added myself to the list of authors in the documentation.
=> changed version

configure.ac, doc/source/mach_walkthrough.txt
=> added enable-logging option to autotools build

src/clib/pio_msg.c
=> free recently allocated vars

src/clib/pioc_sc.c
more reasonable calculation of maxblocksize.   
merged to develop
Fixes issue #1246
=> more reasonable maxblock value

ctest/runcdash-nwsc-gnu.sh
=> modify script for use on cheyenne

src/clib/pio_darray_int.c
Some of my warning fixes caused some fortran tests to breaks.
This PR does an undo of the warning fixes to pio_darray_int.c.
I will swing around again and address those warnings more carefully next time.
=> undo broken warning fix

Makefile.am, src/Makefile.am, src/clib/Makefile.am, tests/Makefile.am, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_intercomm2.c
Fixes for a bunch of autotools issues. Should have no effect on CMake builds.
Fixes #1271.
Fixes #1270.
Fixes #1263.
Fixes #1264.
Fixes #1266.
=> Fixes to autotools build system

examples/c/darray_no_async.c, examples/c/examplePio.c, src/clib/pio_darray.c, src/clib/pio_nc.c
=> Fix fillvalue in write_darray()

src/clib/pio_darray_int.c
This PR aggregates the filetypes of consecutive variables if the variables are of the same NC data type. It is only developed to support writes. It appears that PIO currently reads one variable a time, so I did not try to do the same for reads.
Note this PR is built on top of #1305, so #1305 can be safely skipped.
=> aggregate filetypes of multiple variables for vard API

src/clib/pio_darray.c
Add PnetCDF support for additional datatypes per issue #1314 
Fixes #1314
=> modify to address issue 1314

CMakeLists.txt
Fixed version number in CMake build. Part of #1332
=> changed pio version to 2.4.0 in cmake

src/clib/pio_getput_int.c
Fixing warning to trigger CI run, but it's a real warning. ;-)
=> fixed codacy warning

src/clib/Makefile.am, src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_lists.c, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, src/clib/uthash.h, tests/performance/pioperformance.F90
Convert several linked lists in PIO to hashtables using uthash from https://github.com/troydhanson/uthash
This will be a little slower for tests and small cases but will be much faster with large numbers of files/iodescs/variables/buffers
=> Hashtables

.travis.yml, src/clib/pio_nc.c, src/clib/pio_rearrange.c, src/clib/pioc_support.c
impi doesn't like it when you call MPI_Type_size with MPI_DATATYPE_NULL.
=> Type size fix

.travis.yml, tests/cunit/test_pioc.c
Found some memory leaks in my last PR. Dang it.
I'll move a little more slowly.
Also trying to get cmake build working in travis.
=> trying cmake build in travis

src/clib/pioc_support.c
Fixes #1348.
With this PR, I have no more warnings on my build.
I will merge to develop when this passes my own CI.
=> fixed fscan warnings in pioc_support.c

examples/c/run_tests.sh, src/clib/pio_getput_int.c, src/clib/pio_msg.c, src/clib/pio_rearrange.c, tests/cunit/run_tests.sh, tests/general/test_memleak.c
Some fixes identified by codacy. I have merged to develop branch.
Fixes #1362
=> Some fixes identified by codacy

.travis.yml, README.md, src/clib/pio_lists.c, src/clib/pio_rearrange.c, tests/cunit/test_darray_async_many.c, tests/cunit/test_decomps.c, tests/cunit/test_perf2.c
=> Fixing memory leak in test_darray_async_many.c

src/clib/pio_darray_int.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/test_darray_multi.c, tests/cunit/test_darray_multivar3.c, tests/cunit/test_perf2.c
Part of #1368.
Fixed a memory problem in a logging statement. Also fixed some code warnings.
=> Fix memory issue in logging statement and some warnings

tests/cunit/pio_tests.h, tests/cunit/test_darray_async.c, tests/cunit/test_rearr.c
Fixing some more codacy warnings in tests. I will merge to develop.
=> Fixing some more codacy warnings in tests

src/clib/pio_getput_int.c, src/clib/pio_msg.c, src/clib/pioc.c, src/clib/topology.c
=> Fixing more codacy warnings

src/clib/pioc_support.c, tests/cunit/test_rearr.c
More fixes from codacy.
I have merged with develop for testing.
=> Fix memory leaks on error in test_rearr.c

tests/cunit/test_async_manyproc.c, tests/cunit/test_async_multi2.c, tests/cunit/test_async_multicomp.c, tests/cunit/test_async_simple.c, tests/cunit/test_darray_fill.c, tests/cunit/test_decomp_frame.c, tests/cunit/test_pioc_putget.c
=> More codacy warning fixes

tests/cunit/test_async_mpi.c, tests/cunit/test_decomp_uneven.c, tests/cunit/test_iosystem3.c, tests/cunit/test_pioc_putget.c
=> more codacy warning fixes in test code

tests/cunit/test_perf2.c
Some changes to performance program.
=> Some changes to performance program

configure.ac, src/Makefile.am, src/gptl/Makefile.am, src/gptl/f_wrappers_2.c, tests/Makefile.am, tests/performance/Makefile.am
This builds for me. Testing will follow.
=> First pass at building pioperformance with autotools and externally installed GPTL

src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pio_rearrange.c, src/clib/pioc_sc.c, tests/cunit/test_spmd.c
Cherry-pick some of the optimizations from the e3sm fork.
=> Box optimization

configure.ac, src/gptl/Makefile.am, src/gptl/f_wrappers_2.c, src/gptl/perf_mod.F90, tests/performance/Makefile.am, tests/performance/Pioperformance.md, tests/performance/pioperf.nl, tests/performance/pioperformance.F90, tests/performance/run_tests.sh
More work on pioperformance in autotools build, plus some documentation.
Part of #1390.
Part of #1392.
=> More work on pioperformance in autotools build, plus some documentation

configure.ac, examples/c/Makefile.am, tests/cunit/Makefile.am, tests/general/Makefile.am, tests/performance/Makefile.am, tests/unit/Makefile.am
=> allow tests to be built but not run in autotools build

doc/Doxyfile.in, src/clib/pio_nc4.c, tests/cunit/test_perf2.c
=> more doc fixes

tests/cunit/run_tests.sh, tests/cunit/test_async_manyproc.c, tests/cunit/test_common.c, tests/cunit/test_perf2.c, tests/performance/pioperf.nl
=> performance program changes and turned on test_async_manyproc

configure.ac
=> changed AC_PROG_LIBTOOL to LT_INIT

src/clib/pio_msg.c, tests/cunit/Makefile.am, tests/cunit/test_async_perf.c, tests/cunit/test_perf2.c
Part of #1390
Part of #1341 
Added an async performance test, and fixed stack overflow issue in pio_msg.c.
=> async performance test

configure.ac, tests/cunit/test_async_perf.c
=> more performance test development for async

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_file.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_rearrange.c, src/clib/pio_spmd.c, src/clib/pioc.c, src/clib/pioc_sc.c, src/clib/pioc_support.c, tests/cunit/test_pioc.c, tests/cunit/test_rearr.c, tests/cunit/test_spmd.c
Fixes #1425.
Part of #1410.
Combine error checking functions check_mpi() and check_mpi2().
This will reduce the many differences between master and #1410.
=> combined check_mpi() and check_mpi2()

configure.ac, doc/Doxyfile.in, src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pioc_support.c
Part of #1219.
No code changes, just documentation stuff.
=> more documentation work

.travis.yml
Part of #1219.
Stricter documentation check in travis.
=> changed --enable-docs to --enable-developer-docs

doc/source/Error.txt, doc/source/Installing.txt, doc/source/Makefile.am, doc/source/Testing.txt, doc/source/iosystem.txt, doc/source/users_guide.txt
Part of #1219.
Adding a section about IOsystems.
More coming.
=> added section to user guide about iosystems

src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_nc.c, src/clib/pioc.c, src/flib/pio_nf.F90, src/flib/pio_support.F90, src/flib/piodarray.F90.in
Part of #1219. This is in line behind PR #1458.
No code changes, just documentation changes.
=> More fortran documentation changes

doc/source/api.txt, src/flib/pio.F90, src/flib/pio_nf.F90, src/flib/piolib_mod.F90
Part of #1219.
Just doc changes, no code changes.
=> More fortran doxygen stuff

doc/Doxyfile.in, doc/source/api.txt, src/clib/pio_darray.c, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_nc.c, src/clib/pio_put_nc.c, src/clib/pioc.c, src/flib/pio.F90, src/flib/pio_nf.F90, src/flib/pio_types.F90, src/flib/piodarray.F90.in, src/flib/piolib_mod.F90, src/flib/pionfatt_mod.F90.in, src/flib/pionfget_mod.F90.in, src/flib/pionfput_mod.F90.in
Getting close to the end, but still more to go.
Part of #1219.
All documentation changes in this PR, no code changes.
=> more documentation changes

src/flib/piodarray.F90.in, src/flib/piolib_mod.F90
=> removed home-rolled memory checking code

configure.ac, src/clib/CMakeLists.txt, src/clib/Makefile.am, src/clib/pio.h, src/clib/pio_darray.c, src/clib/pio_get_vard.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_nc.c, src/clib/pio_put_nc.c, src/clib/pio_put_vard.c, tests/cunit/Makefile.am, tests/cunit/run_tests.sh, tests/cunit/test_darray.c, tests/cunit/test_darray_vard.c
Part of #1469.
Still adding tests and then have to enable data conversion.
=> new vard functions

Makefile.am, src/clib/pio.h, src/flib/pio_types.F90
Fixes #1478.
Also some whitespace cleanup and fixed comment in pio.h.
=> Fix attempted removal of docs directory

src/flib/pio_types.F90
=> Cleanup of pio_types.F90

configure.ac, tests/cunit/test_perf2.c
=> added MPE to test_perf2.c

src/clib/pio_internal.h, src/clib/pioc.c, src/clib/pioc_support.c
=>  now pio_init_logging() checks are returns error codes 

src/flib/piolib_mod.F90
=> fixed fortran decomp docs

CMakeLists.txt, configure.ac, src/clib/Makefile.am, src/flib/Makefile.am
=> update version numbers

CMakeLists.txt, configure.ac
Changed version to prepare for next release.
=> changed versions

src/clib/pio_internal.h, src/clib/pioc_support.c, tests/cunit/pio_tests.h, tests/cunit/test_async_perf.c, tests/cunit/test_common.c, tests/cunit/test_perf2.c
Fixes #1497.
This is yielding some great insights into what is going on in the code. I'm very happy with the results!
=> Now enable MPE logging in test_async_perf.c

examples/c/darray_no_async.c, src/clib/pio_error.h, tests/general/pio_decomp_frame_tests.F90.in, tests/general/pio_decomp_tests_2d.F90.in, tests/general/pio_decomp_tests_3d.F90.in, tests/general/pio_iosystem_tests.F90.in, tests/general/pio_iosystem_tests2.F90.in, tests/general/pio_iosystem_tests3.F90.in
Fixes #1524 
Fixes #1523 
Part of #1522 
Fixes #1521 
Fixes #1519 
Fixes some more Fortran warnings.
=> Fix more fortran warnings

tests/general/pio_decomp_frame_tests.F90.in, tests/general/pio_decomp_tests.F90.in, tests/general/pio_decomp_tests_1d.F90.in, tests/general/pio_rearr_opts.F90.in, tests/general/pio_rearr_opts2.F90.in
Fixes #1528 
Fixes #1527 
Fixes #1526 
Fixes #1524 
Fixes #1523 
Part of #1522 
More warning fixes. Still more to come. I'm going to start merging the earlier PRs with warning fixes...
=> even more fortran warning fixes

src/flib/pionfput_mod.F90.in, tests/general/ncdf_get_put.F90.in, tests/general/ncdf_inq.F90.in, tests/general/pio_rearr.F90.in, tests/general/util/pio_tutil.F90
Fixes #1532 
Fixes #1531 
Fixes #1530 
Part of #1522 
More warning fixes for Fortran code. More to come.
=> more fortran warning fixes

src/clib/pio_internal.h, src/clib/pio_rearrange.c, tests/cunit/test_rearr.c
now find_region() returns error code, and takes pointer to regionlen as a parameter
Fixes #1501.
=> now find_region() returns error code, and takes pointer to regionlen as a parameter

src/flib/piolib_mod.F90
Fixes #1538.
Part of #1537 
Fixes for warnings in piolib_mod.F90, including commenting out a bunch of non-functional code.
=> fixes for warnings in piolib_mod.F90

src/flib/piolib_mod.F90, tests/general/util/pio_tutil.F90
Fixes #1515 
Fixes the warnings in pio_tutil.F90.
=> more warning fixes

.travis.yml, src/flib/pio_nf.F90, src/flib/pio_support.F90, src/flib/piolib_mod.F90, tests/general/util/pio_tutil.F90
Fixes #1514 
Fixes #1511 
Fixes some warnings and also turned on -Werror for the C compiler in travis (which already is building without C warnings).
=> More fortran warnings, also turn on -Werror for C code

src/flib/piodarray.F90.in, src/flib/piolib_mod.F90
Fixes #1510 
Fixes #1537.
Fix for last of the fortran warnings.
=> fixed warnings in piodarray.F90.in

.travis.yml, examples/c/darray_async.c
Trying (again) to get Travis to enforce warning-free builds.
=> turning on -Werror for C compiler

src/clib/pio_spmd.c, tests/general/pio_decomp_fillval.F90.in
=> clean up some old code

src/clib/bget.c, src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_error.h, src/clib/pio_file.c, src/clib/pio_get_nc.c, src/clib/pio_get_vard.c, src/clib/pio_getput_int.c, src/clib/pio_internal.h, src/clib/pio_lists.c, src/clib/pio_msg.c, src/clib/pio_nc.c, src/clib/pio_nc4.c, src/clib/pio_put_nc.c, src/clib/pio_put_vard.c, src/clib/pio_rearrange.c, src/clib/pio_spmd.c, src/clib/pioc.c, src/clib/pioc_sc.c, src/clib/pioc_support.c, src/clib/topology.c, tests/cunit/test_async_perf.c, tests/cunit/test_darray_async.c, tests/cunit/test_darray_async_many.c, tests/cunit/test_rearr.c
Fixes #1553 
Simple rename of some macros, no other code changes.
=>  rename LOG and BAIL macros to PLOG and PBAIL

src/clib/Makefile.am
=> now install uthash.h

configure.ac, src/Makefile.am, src/clib/Makefile.am, src/clib/pio.h, src/clib/pioc.c, src/ncint/ncint_pio.c, src/ncint/ncintdispatch.c, tests/ncint/Makefile.am, tests/ncint/tst_pio_udf.c
Part of #1556 
Some changes in the C library needed to support netCDF/PIO integration in Fortran.
=> Further development of netCDF integration in C library, to support Fortran

src/flib/CMakeLists.txt, src/flib/pio.F90, src/flib/piolib_mod.F90
Part of #1555 
getting netCDF integration working in fortran
=> getting netCDF integration working in fortran

src/clib/pioc.c, src/flib/ncint_mod.F90, src/flib/pio.F90, src/ncint/ncint_pio.c, src/ncint/ncintdispatch.c, tests/fncint/ftst_pio.f90
Part of #1555.
Added nf_free_decomp().
Also added contents for PIO_NCINT_inq_format_extended() and PIO_NCINT_inq_format().
=> added nf_free_decomp() to netCDF integration API

configure.ac, examples/Makefile.am, examples/f03/Makefile.am, examples/f03/run_tests.sh
Fixes #1572.
Got the fortran example working in the autotools build.
=> got fortran example working in autotools build

src/clib/pioc_support.c
=> remove hardcoded timer name

src/clib/pio.h, src/ncint/ncint_pio.c, src/ncint/ncintdispatch.c, tests/ncint/Makefile.am, tests/ncint/pio_err_macros.h, tests/ncint/tst_pio_async.c, tests/ncint/tst_pio_udf.c
Part of #1555.
Starting to get async working with netcdf integration.
=> starting to get async working with netcdf integration

src/clib/pio_rearrange.c
Fixes issue #1583 as reported by summit developers.
=> fix an integer overflow issue reported on summit

configure.ac, src/clib/Makefile.am, src/flib/Makefile.am
Changed version numbers for release.
Part of #1585
=> changed versions for release

src/ncint/ncint_pio.c, tests/fncint/Makefile.am
Last minute fixes for release.
Part of #1585
=> last minute fixes

src/clib/pio_file.c, src/clib/pio_msg.c, src/clib/pioc_support.c, src/ncint/ncintdispatch.c
Part of #1555.
I need to change how PIOc_createfile() gets called in async mode. This will support netCDF integration.
=> Minor change in how createfile works in async mode

src/clib/pio_darray.c
=> fixed warning in pio_darray.c

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_msg.c, src/clib/pio_rearrange.c, src/clib/pioc_support.c, tests/cunit/test_async_1d.c, tests/ncint/tst_pio_async.c
Part of #1598 
This is an implementation of read_darray() with some tests.
More tests to follow to confirm this works properly in more complex cases.
=> implementation of read_darray() and some tests

src/clib/pio_msg.c, src/clib/pioc_support.c, tests/ncint/Makefile.am, tests/ncint/run_tests.sh, tests/ncint/tst_async_multi.c, tests/ncint/tst_pio_udf.c
Part of #1555.
In this PR I add a test which uses async mode and opens two computational components using netCDF integration. This requires some special handling of the iosysid for creates/opens.
Also added a test for this capability. More tests will be coming in future PRs.
=> getting netCDF integration working for async mode with multiple computational components

src/clib/pio.h
Part of #1576 
Documentation changes only in this PR.
=> fixed some documentation warnings

CMakeLists.txt, configure.ac, src/clib/Makefile.am, src/clib/pio_internal.h, src/ncint/ncintdispatch.c
=> changed version numbers for 2.5.0 release

tests/ncint/tst_ncint_perf.c
Improvements to performance program. No library changes in this PR.
=> improvements in performance program

src/clib/pioc_support.c, tests/ncint/tst_ncint_perf.c
Again, improvements in performance program. No library code changes.
=> More performance program improvements

src/clib/pio.h, src/ncint/ncint_pio.c, tests/ncint/Makefile.am, tests/ncint/run_perf.sh, tests/ncint/tst_ncint_async_perf.c, tests/ncint/tst_ncint_perf.c, tests/ncint/tst_pio_udf.c
In this PR I add a benchmarking program for netCDF integration. Also corrected a typo in one of the ncint functions.
=> adding additional benchmarking program for netcdf integration

src/clib/pio_rearrange.c
=> moved decl for performance

tests/cunit/test_async_3proc.c, tests/cunit/test_async_4proc.c, tests/cunit/test_async_simple.c, tests/cunit/test_pioc.c, tests/cunit/test_pioc_fill.c, tests/cunit/test_pioc_putget.c
=> fixed warnings in tests

CMakeLists.txt, configure.ac, src/clib/Makefile.am, src/flib/Makefile.am
=> updated version numbers

examples/c/example2.c, src/clib/pio_nc.c, src/flib/Makefile.am, src/flib/pio_types.F90, src/flib/piolib_mod.F90, src/flib/pionfput_mod.F90.in
Documentation fixes to get warning-free documentation build.
=> Ejh doc fixes

CMakeLists.txt, configure.ac, libpio.settings.in, src/clib/pio_meta.h.in
Fixes #1687 
Part of #1658 
Adding to the list of features in the build.
=> Add netcdf-4 and netcdf-4 par features to the build summary and to pio_meta.h

.travis.yml, tests/ncint/tst_ncint_async_perf.c, tests/ncint/tst_ncint_perf.c, tests/unit/basic_tests.F90
=> fixed memory leaks in tests/ncint/tst_ncint_async_perf.c and tests/ncint/tst_ncint_perf.c

.github/workflows/autotools.yml, .travis.yml, CMakeLists.txt, configure.ac, tests/cunit/test_pioc.c, tests/unit/ncdf_tests.F90
=> disallow netcdf-c-4.7.2 for both cmake and autotools builds

src/flib/Makefile.am
=> fixed makefile

cmake_config.h.in
=> including HAVE_PAR_FILTERS in cmake config.h

.travis.yml, configure.ac, libpio.settings.in
=> removed unused define, clarified build summary, cleaned up some aspects of travis build

configure.ac, examples/basic/gdecomp_mod.F90, examples/basic/testpio.F90, src/flib/Makefile.am, src/flib/pio.F90, tests/cunit/test_common.c, tests/cunit/test_iosystem3.c, tests/general/util/pio_tutil.F90, tests/unit/driver.F90
=> removed unneeded pre-processor flag _NETCDF (because netCDF is always present)

cmake_config.h.in
=> removed unneeded pre-processor symbol from cmake_config.h.in

.github/workflows/cmake.yml, CMakeLists.txt, src/clib/CMakeLists.txt, src/flib/CMakeLists.txt, src/gptl/CMakeLists.txt
Reduce the number of calls to find_package(NetCDF) to one at the top level. 
Fixes: #1724
=> Reduce search netcdf

.github/workflows/a3.yml, .github/workflows/autotools.yml, .github/workflows/cmake.yml, .github/workflows/cmake_ncint.yml, .github/workflows/strict_autotools.yml, CMakeLists.txt, configure.ac, examples/c/Makefile.am, examples/c/run_tests.sh.in, tests/cunit/Makefile.am, tests/cunit/run_tests.sh.in
In this PR I add openmpi testing with GitHub actions (#1675).
Also, to make this work, I add the --with-mpiexec= option to configure (see #1732).
=> Add C testing with openmpi-4.0.4, netcdf-c-4.7.4, pnetcdf-1.12.1

.github/workflows/a3.yml, configure.ac, src/flib/pionfget_mod.F90.in, tests/ncint/Makefile.am, tests/ncint/run_perf.sh.in, tests/ncint/run_tests.sh.in
Part of #906
Fixes #1632 
Part of #1675 
In this PR I fix some docs and add some testing. ;-)
=> fixing docs, cleanup of test workflow

.github/workflows/a4.yml, CMakeLists.txt
=> fixing MPIEXEC in library summary for CMake builds

.github/workflows/a4.yml, src/clib/CMakeLists.txt, src/flib/CMakeLists.txt, tests/cunit/CMakeLists.txt
=> Adding more github testing

.github/workflows/a4.yml, configure.ac
=> added check for MPI

src/flib/pio_nf.F90, src/flib/piolib_mod.F90
=> Fortran documentation improvments

src/flib/pio_nf.F90
Add a fortran interface to set_fill function.
Fixes #1758
=> add set_fill to fortran interface

src/flib/pio_nf.F90
=> fix integer overflow issue noted in nag compiler

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pioc.c, tests/cunit/CMakeLists.txt
Some tests were not being run because the macro had not full been removed
Fixes #1760
=> fully remove pio_use_malloc macro

ctest/runcdash-nwscla-gnu.sh, ctest/runcdash-nwscla-intel.sh, ctest/runcdash-nwscla-pgi.sh
Update cheyenne modules for cdash tests
=> update cheyenne modules for ctest

ctest/runcdash-nwscla-pgi.sh, tests/unit/global_vars.F90
openmpi was not happy with #include "mpif.h" - replacing with use mpi solved the problem.
pgi version string needed fixed for pgi-20
=> fix pgi version and openmpi test error

src/clib/pio_darray.c, src/clib/pio_rearrange.c, src/flib/pio.F90, src/flib/piodarray.F90.in, src/flib/piolib_mod.F90, src/flib/pionfatt_mod.F90.in, src/flib/pionfget_mod.F90.in, tests/general/pio_decomp_fillval.F90.in, tests/general/util/pio_tf_f90gen.pl, tests/general/util/pio_tutil.F90
tested with cheyenne intel and netcdf 4.7.3 pnetcdf 1.12.1 mpt 2.22
=> implement pio_inq_var_fill in fortran, add tests

src/clib/pio_getput_int.c, src/flib/pio.F90, src/flib/pio_nf.F90, src/flib/pio_types.F90, src/flib/pionfget_mod.F90.in, src/flib/pionfput_mod.F90.in, tests/general/ncdf_get_put.F90.in, tests/general/util/pio_tf_f90gen.pl
Fix more issues found in fortran interface.
=> More fortran interface

src/clib/pio_rearrange.c, src/clib/pioc.c, tests/performance/pioperformance.F90
Change in initialization on io tasks.
=> Async fixes

.github/workflows/strict_autotools.yml, src/flib/ncint_mod.F90, src/flib/pio.F90, src/flib/pio_types.F90, tests/fncint/ftst_pio.f90
=> add nf_pio, netcdf now defines cdf5 format

src/clib/pio_nc.c, src/clib/pio_rearrange.c, src/clib/pioc.c, tests/cunit/test_async_4proc.c, tests/cunit/test_async_multicomp.c, tests/cunit/test_rearr.c
subset rearranger working now in async mode. 
Fixes #1789
=> subset working in async

tests/cunit/test_async_perf.c, tests/cunit/test_perf2.c
Fixes #1793 
Some minor fixes to make getting performance data easier.
=> Some minor fixes to test_perf2.c and test_async_perf.c

src/clib/pio.h, src/clib/pio_rearrange.c, src/clib/pioc.c, src/clib/pioc_support.c, tests/cunit/CMakeLists.txt, tests/cunit/test_async_perf.c, tests/cunit/test_darray_async_many.c
Add subset rearranger to test_darray_async_many.c
=> add SUBSET rearranger

tests/cunit/test_async_perf.c, tests/cunit/test_perf2.c
updated documentation and cleaned unneeded preprocessor symbols from test_perf2 and test_async_perf
=> updated documentation and cleaned unneeded preprocessor symbols from test_perf2 and test_async_perf

tests/cunit/pio_tests.h, tests/cunit/test_perf2.c
=> fixes to test_perf2.c

configure.ac, tests/cunit/pio_tests.h, tests/cunit/test_async_perf.c, tests/cunit/test_perf2.c, tests/cunit/test_simple.c
More work on performance programs.
Part of #1803
Part of #1808
=> modification to perf program output, fix perf timing, add chunksizes for netCDF-4/HDF5 files

src/clib/pio_darray.c, src/clib/pioc.c, src/flib/piolib_mod.F90, tests/unit/driver.F90
Fixes #1815 
Fixes #1813 
Fix some warnings, add some clarifications to the docs.
=> Fix warnings, documentation improvements

src/clib/pioc_sc.c
Fixes #1236 
Increased the DEFAULT_BLOCKSIZE.
=> changed default blocksize

tests/cunit/run_tests.sh.in, tests/cunit/test_darray_multivar3.c
There were a bunch of things wrong with this test, and it was not being run. Now I've fixed the test and it will be run with the rest of the tests.
Fixes #1372 
Fixes #1678
=> Fixes to test_darray_multivar3.c

.github/workflows/netcdf-4.7.4_hdf5-1.12.0_pnetcdf-12.1_ncint_mpich-3.3.yml, .github/workflows/netcdf-4.7.4_hdf5-1.12.0_pnetcdf-12.2_ncint_mpich-3.3.yml
=> adding testing

.github/workflows/cmake_netcdf-4.7.4_hdf5-1.10.7_pnetcdf-12.1_ncint_mpich-3.3_asan.yml, configure.ac, tests/cunit/CMakeLists.txt, tests/cunit/test_darray_multivar.c, tests/ncint/tst_var_compress.c
Part of #1728
Added a new cmake build workflow which builds dependent libraries.
Fixes #1838 
Fixed some code warnings.
=> adding cmake build, fix code warnings

src/clib/pio_darray_int.c, tests/fncint/ftst_pio_orig.f90
=> fixed warnings and netcdf-integration build without pnetcdf

configure.ac, src/flib/Makefile.am, tests/cunit/test_async_1d.c
=> cleanup of automake and pre-processor symbols

src/clib/pio_msg.c, tests/cunit/test_async_1d.c, tests/ncint/tst_async_multi.c, tests/ncint/tst_pio_async.c
Dealing with stack smashing in async code
Fixes #1847
=> fixing wrong type of parameter in async read_daray_handler, turning test code back on

tests/cunit/test_async_1d.c
=> turned test code back on

tests/unit/ncdf_tests.F90
Remove the redef from def test, this is no longer an error issue.
Fixes #1804
=> remove this test, no longer valid

src/clib/pioc_support.c
Only create log files if log level > 0.
=> only create log files if log level > 0

CMakeLists.txt
=> fix indicator for pnetcdf support in cmake

CMakeLists.txt, configure.ac, src/clib/Makefile.am, src/flib/Makefile.am
Part of #1818 
Changing version numbers for release.
=> updated version numbers for release of 2.5.3

.github/workflows/autotools.yml, .github/workflows/cmake.yml, .github/workflows/strict_autotools_ubuntu_latest.yml, CTestScript.cmake, cmake/LibMPI.cmake, cmake/TryNetCDF_DAP.c, src/clib/pio_getput_int.c
Fix issue in detecting dap and in collective comm in getput_int
Fixes #1863 
Fixes #1861
=> fix error in check_netcdf call and in detecting dap

configure.ac
=> fixed version

examples/f03/Makefile.am
Fixes #1874
add exampleAsyncPio.F90 to the autotools build
=> add exampleAsyncPio.F90 to the autotools build

configure.ac, tests/cunit/test_darray_async_many.c
Fixes #1867 
Fix integer overflow in test code which causes problems for intel compiler.
=> fixed overflow in test tests/cunit/test_darray_async_many.c

src/clib/pio_darray.c, src/clib/pio_darray_int.c, src/clib/pio_internal.h, src/clib/pioc_support.c
=> rename pio_buffer_size_limit to pio_pnetcdf_buffer_size_limit

.github/workflows/autotools.yml, .github/workflows/cmake.yml, .github/workflows/cmake_ncint.yml, .github/workflows/cmake_netcdf-4.7.4_hdf5-1.10.7_pnetcdf-12.1_ncint_mpich-3.3_asan.yml, .github/workflows/netcdf-4.7.4_hdf5-1.10.7_pnetcdf-12.1_ncint_mpich-3.3_asan.yml, .github/workflows/netcdf-4.7.4_hdf5-1.12.0_no_pnetcdf_ncint_mpich-3.3.yml, .github/workflows/netcdf-4.7.4_hdf5-1.12.0_pnetcdf-12.2_ncint_mpich-3.3_asan.yml, .github/workflows/netcdf-4.7.4_pnetcdf-12.1_ncint_mpich-3.3.yml, .github/workflows/netcdf-4.7.4_pnetcdf-12.1_ncint_openmpi_4.0.4.yml, .github/workflows/strict_autotools_ubuntu_latest.yml, configure.ac, tests/cperf/piodecomptest.c
=> update netcdf download path

src/clib/pio_darray_int.c, src/clib/pio_rearrange.c, tests/cperf/piodecomptest.c, tests/performance/pioperformance.F90
Fixes issue #1910 
We should prepare for a 2.5.6 release with this change.
=> fix for subset rearranger bug in 2.5.5

CMakeLists.txt, configure.ac
Updates the version to 2.5.6 for new release.
=> update version to 2.5.6

CMakeLists.txt
I was able to test with cmake 3.5.2 and so will set that as minimum cmake required.
=> closer to requred cmake minimum

CMakeLists.txt, configure.ac
Update version in configure.ac and CMakelists.txt
=> update version to 2.5.7

CMakeLists.txt, configure.ac
=> update pio version to 2.5.8

CMakeLists.txt
=> Add BUILD_SHARED_LIBS option

CMakeLists.txt, src/clib/CMakeLists.txt, src/clib/pio_darray.c, src/flib/CMakeLists.txt, src/flib/pio_support.F90, tests/cperf/piodecomptest.c, tests/performance/pioperformance.F90
Some clean up and cmake build changes.  These are based on experience building with spack.
=> updates based on experiences with spack package

CMakeLists.txt, configure.ac
=> update version tags

CMakeLists.txt, configure.ac
=> update version patch to 10

src/flib/piolib_mod.F90
=> correct create mode documentation

doc/source/Introduction.txt
=> update the pnetcdf link in documentation;
