NCAR/ParallelIO

- doc/source/Decomp.txt
- doc/source/Installing.txt
- src/flib/CMakeLists.txt
- src/gptl/CMakeLists.txt
- tests/performance/pioperformance.F90
Looks like I only had one of the two lines that needed shortening in my commit yesterday. This pull request has the other, plus the added -mismatch_all flag for the NAG compiler. My testing today indicated that these changes helped get the basic tests to run through and pass. I will update the issue post!
> Changes to CMakeLists for NAG compiler and shortening a line

- src/clib/CMakeLists.txt
This branch implements a change to include the C-template code, used to generate the 'pio_nc.c', 'pio_put_nc.c' and 'pio_get_nc.c' files when generating C-code from templates, as dependencies for the 'pioc' library. 
Originally, the 'execute_process' command was used to copy these 3 files from the CMAKE_CURRENT_SOURCE_DIR to the CMAKE_CURRENT_BINARY_DIR before building (and the 'pioc' library depended on the CMAKE_BINARY_DIR location of these files).  Unfortunately, the 'execute_process' command does not properly recognize the original files (in the SOURCE dir) as dependencies for the copied files.  Thus, changes to the files in the SOURCE dir were not recopied to the BINARY dir when building.
Fortunately, this type of template-based code generation is done in the 'piof' library with …
> Changing the C-generated code command to include dependencies on templates

- src/clib/ncparser.pl
- src/clib/pio_nc.c
This commit includes the newly reformed doxygen documentation for pio_nc plus support for parallel-netcdf 1.6.1 in ncparser.pl. However, the version of pio_nc.c checked in is built with parallel-netcdf 1.6.0, which is the most commonly used version.
> pio_nc updates to documentation 

- ctest/runcdash-nwsc-intel-mpiserial.sh
- src/clib/pio_lists.c
- src/clib/pio_spmd.c
- src/clib/pioc.c
- src/flib/piolib_mod.F90
- tests/general/util/pio_tutil.F90
Fixes to get the nightly tests to run through on Caldera with serial MPI. Better handling of bad task configurations at init time, plus added logic to the test that prevents asking for bad configurations when running serially. Also includes a few updates to Doxygen comments in the spmd module as I was reading through it last week. These changes pass all nightly/unit tests on Caldera.
> Fixes to get the nightly tests to run through on Caldera with serial MPI

- pio/box_rearrange.F90.in
- pio/calcdecomp.F90
- pio/ionf_mod.F90
- pio/pio.F90
- pio/pio_msg_callbacks.F90
- pio/pio_msg_mod.F90
- pio/pio_types.F90
- pio/piodarray.F90.in
- pio/piolib_mod.F90
- pio/pionfatt_mod.F90.in
- pio/pionfput_mod.F90.in
- pio/pionfwrite_mod.F90.in
- pio/rearr_options.h
This change brings in all ACME changes in PIO1 to the PIO1 branch
(pio1_0).
* Moving PIO rearranger options from compile-time to runtime.
The rearranger options can now be provided via an optional
argument to PIO_init()
* Some additional timers in PIO
* Changing __FILE__ to __PIO_FILE__ to overcome build failures with
pgi
> Bringing in ACME changes to PIO1 branch

- src/clib/ncparser.pl
- src/clib/pio_nc.c
- tests/unit/CMakeLists.txt
- tests/unit/test_names.c
In current code, the null terminator is not broadcast to tasks where rank != 0 for serial formats on PIOc_inq_varname/dimname/attname.
> Fix lengths of names of atts/vars/dims sent to tasks where rank != 0 for serial io types

- src/clib/pio_nc4.c
- src/flib/pio.F90
- src/flib/pio_nf.F90
- tests/unit/driver.F90
- tests/unit/ncdf_tests.F90
- tests/unit/test_nc4.c
PIO_inq_var_deflate works in fortran. The fortran version is tested in ncdf_tests.F90 in a new test subroutine test_nc4.
There are some szip-related functions for netCDF-4 that I had added to the PIO C API. After further consideration I have taken them out again. I don't think there will be much of a use among the PIO audience.
Szip files are used a lot by NASA, but the only consequence of not having the inq_szip functions is that programs like ncdump cannot be written without it. However, I doubt anyone will be writing a version of ncdump for PIO. Szipped data will still be readable by PIO - the szip decompression of the data is done automatically in the HDF5 layer.
Thanks to this fortran work and some emails with Jim, I have a better understanding of how error codes are supposed to work …
> Fortran implementation if inq_var_deflate, removed szip functions, fixed C bug in inq_deflate

- examples/c/example2.c
- examples/c/valsupp_example1.supp
The example test was taking noticeable time so I reduced the sample size.
I added the valgrind suppression file to allow me to use valgrind on an on-going basis to make sure I'm not leaking memory in any of the async work.
> changed example data size, added valgrind suppression file

- src/clib/pio_file.c
- src/clib/pio_internal.h
These changes do not affect non-async operation, but are necessary for async.
The changes are mostly sending the contents of the parameters to the io tasks, and sending back the resulting information, if any.
Some new MSG constants are added to support some missing functions in the original list.
> changing in pio_file.c to support async

- src/clib/pio_get_nc_async.c
- src/clib/pio_lists.c
- src/clib/pio_nc_async.c
- src/clib/pio_put_nc_async.c
- src/clib/pioc.c
In this pull request there are changed for pioc.c, mostly in the finalize function. The changes to compmaster and iomaster are in accordance with MPI docs and pass all tests. 
There is also a change to pio_lists.c, which used to change the ncids when run with async. That doesn't work with the async code I wrote, so I have taken it out and cleaned up the function, as well as addind documentation.
The pull request also includes copies of three code files, which will be used for async development. The original code files are generated by perl scripts. After async development is complete, I will modify the perl scripts to output the async-capable code, and remove these three files. For now I would like to merge them to master before I make async changes, so you can easily see the changes that …
> changes to pioc.c, pio_lists.c to support async, also some temporary code

- src/clib/pio_file.c
- src/clib/pio_nc_async.c
- tests/unit/basic_tests.F90
As discussed, change basic_tests.f90 so that ret_val does not get overwritten when there is an error.
> now MPI_abort does not overwrite ret_val

- doc/CMakeLists.txt
- doc/Doxyfile.in
- src/clib/pio_darray_async.c
This is a fix for github issue:
https://github.com/NCAR/ParallelIO/issues/85
> Fix build of documentation for async vs. non-async builds

- src/clib/pio.h
- src/clib/pioc_support.c
- src/flib/pio.F90
- src/flib/pio_nf.F90
- tests/unit/driver.F90
- tests/unit/test_names.c
This PR adds PIO wrappers for the nc_strerror() function, which gets the error string associated with an error code.
The code is tested in both fortran and C tests.
> Implementation of PIOc_strerror() and pio_strerror() to get strings associated with error codes

- tests/unit/test_names.c
A test I recently put in depended on the value of a netCDF error string. This has changed in a recent version of netCDF.
So I have removed that test.
> removed test that depended on changing netCDF error string

- pio/box_rearrange.F90.in
- pio/pio_types.F90
- pio/piolib_mod.F90
This commit allows the user to separately control the flow
control options for comp2io and io2comp directions.
* The flow control options are now separately defined for
comp2io direction and io2comp direction
* The rearranger options structure (passed during PIO_init())
is also updated accordingly
Note: This change requires corresponding changes in the
share code (in CIME) due to changes in the rearranger opt
structure
> Adding more runtime rearranger options

- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pioc.c
- tests/unit/CMakeLists.txt
- tests/unit/test_file.c
- tests/unit/test_names.c
Here are the wrappers for nc_open and nc_create. They use the same code behind the scenes as PIOc_openfile() and PIOc_createfile() but with a few twists.
An advantage to using these new wrapper functions is that it transparently enables access to the CDF5 format from Argonne parallel-netcdf, even for netCDF sequential.
> wrappers for nc_open/nc_create

- src/clib/pio_file.c
- tests/general/CMakeLists.txt
- tests/general/pio_iosystem_tests.F90.in
- tests/general/pio_iosystem_tests2.F90.in
PIO uses a global file list, pio_file_list (pio_lists.c), to keep track of
files. This list is currently indexed using the file id (file handle) and
the current code implicitly assumes that file handles for files are
unique globally (across all MPI processes).
This commit fixes one part of the problem mentioned in Issue #99 .
This commit also brings in two tests, pio_iosystem_tests.F90 and
pio_iosystem_tests2.F90 . The first test passes now but the
second one fails/hangs.
> Fix dup files in pio file list - part 1

- tests/general/CMakeLists.txt
- tests/general/pio_iosystem_tests3.F90.in
- tests/general/util/pio_tf_f90gen.pl
- tests/general/util/pio_tutil.F90
This change brings in the following changes,
* Re-enables pio_iosystem_tests2
* Adds a new test, pio_iosystem_tests3, that performs tests on iosystems with overlapping processes. This test works with pio1 but hangs with master (pio2_0_15-1049-gd3b1b13).
* Some testing infrastructure changes to improve error reporting
> Tests for IOSystems with overlapped ranks and some testing infrastructure changes

- tests/general/pio_iosystem_tests3.F90.in
Adding support for running the test in serial (MPI_SERIAL +
netcdf) mode. Without this fix the ranges calculated for the
new communicators were invalid for the single proc case.
Fixes #124
> Adding serial support for pio_iosystem_tests3

- tests/unit/pio_tests.h
- tests/unit/test_async_3proc.c
- tests/unit/test_async_4proc.c
- tests/unit/test_async_simple.c
- tests/unit/test_common.c
- tests/unit/test_intercomm2.c
- tests/unit/test_iosystem2_simple2.c
These are some fixes for test code that will (hopefully) make it pass CDash on yellowstone.
In one case the test was not handling the fact that all different iotypes may not be present.
In all other cases the problem had to do with creating the filename of the output test file. The string that provided the iotype name as not being copied correctly and leading to corrupt filenames.
These changes are all to test code - no changes to library code.
> test fixes for cdash

- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_get_nc.c
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- src/clib/pio_nc.c
- src/clib/pio_nc4.c
- src/clib/pio_put_nc.c
- src/clib/pio_varm.c
- src/clib/pioc.c
In the recently rolled-back PR, the following code was being added to check the validity of the iosystem pointer before use.
if (!(file = pio_get_file_from_id(ncid)))
￼          return PIO_EBADID;		￼         
￼      ios = file->iosystem;		￼   
￼ +    if(ios == NULL){
￼ +      fprintf(stderr, "%s:%d ERROR: File has no iosystem attached to it\n", __FILE__, __LINE__);
￼ +      return PIO_EBADID;
￼ +    }
This change was made in many places. Instead, I have modified the pio_get_file_from_id2() function, to check for this condition. (I also renamed it pio_get_file()). Then I changed the code to use that function, and return any error code.
So now this check (for a valid iosystem) is run within the function. A PIO_EINVAL is returned if the iosystem is NULL, which it should never be.
Since this …
> check params - part 1

- src/clib/bget.c
- src/clib/bget.h
- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_get_nc.c
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- src/clib/pio_msg.c
- src/clib/pio_nc.c
- src/clib/pio_nc4.c
- src/clib/pio_put_nc.c
- src/clib/pio_rearrange.c
- src/clib/pio_spmd.c
- src/clib/pio_varm.c
- src/clib/pioc.c
- src/clib/pioc_sc.c
- src/clib/pioc_support.c
- src/clib/topology.c
A good suggestion from the meeting is that reformatting be applied to the entire codebase, without any other changes, as its own pull request.
That is what this is. In emacs I opened each file and ran the following commands:
M-x indent-region (for the whole file)
M-x untabify
M-x delete-trailing-whitespace
So there are no actual code changes. Just a lot of whitespace changes.
> reindented, untabified, and deleted trailing whitespace

- doc/CMakeLists.txt
- doc/Doxyfile.in
When I merged in the async code I forgot to apply this change.
This just removes the special case of the async from the doxygen build file. The documentation continues to build correctly after this change.
This PR is documentation only, no code changes.
Fixes #133.
> removed async stuff from documentation

- src/clib/pioc.c
- src/clib/pioc_support.c
This PR contains documentation fixes to pioc.c and pioc_support.c.
It also includes some whitespace changes, and some removal of detailed logging that I put in when hunting for recent iosystem bugs.
Unfortunately, the doxygen internal flag does not do what we were hoping it did. We must come up with a different way of documenting some functions for developers, and some for the user. I will address that in a new github issue.
> documentation fixes for pioc.c

- tests/unit/test_async_2comp.c
- tests/unit/test_async_3proc.c
- tests/unit/test_async_4proc.c
- tests/unit/test_async_simple.c
- tests/unit/test_common.c
- tests/unit/test_iosystem2.c
- tests/unit/test_iosystem2_simple.c
- tests/unit/test_iosystem2_simple2.c
- tests/unit/test_iosystem3.c
- tests/unit/test_iosystem3_simple.c
- tests/unit/test_iosystem3_simple2.c
As pointed out in github issue #163 some of the C tests were calling MPI_Finalize() twice.
This PR fixes the bugs that caused that, including lack of return statement, and calling ERR() macro on failure of pio_test_finalize() (which will have already called MPI_finalize()).
Fixes #163.
> fixed naughty behavior with finalize

- src/clib/pioc.c
- src/clib/pioc_support.c
From discussion with Jim, it seemed that the use of environment variables in Init_Intracomm() was an old feature, no longer used.
Environment variables are not a good way to control our library functions, so that is probably why their use was abandoned. 
There was never any reference to the environment vars in Init_Intercomm().
This pull request removes this old code.
Fixes #143 
Fixes #138
> removed use of environmental vars

- src/clib/pio_darray.c
- src/clib/pio_file.c
This change ensures that we don't free the iobuf and fillbuf
, for PNETCDF iotype, before waiting on the pending io request.
Also see c0884e57a25e283768b451d4a1bcefb676c6ac8a
Also making sure that flush_output_buffer() is only called for
PNETCDF iotype.
Fixes #179
> Making sure we free buffers only after using them

- tests/unit/CMakeLists.txt
- tests/unit/test_darray.c
- tests/unit/test_darray_async.c
As a prelude for putting some meat on these tests, I have updated them to use the test_common.c, and pio_test.h. This eliminates a bunch of code that was repeated in every C test.
No changes to library functionality in this PR - just test code. This is a prelude to working on #89.
> Modify test_darray and test_darray_async to use test_common.c

- src/clib/pio_darray.c
- tests/unit/test_darray.c
I have added comments to PIOc_write_darray(). Please review the comments and tell me what I got wrong. ;-)
I have used double-question marks where I am confused. If you could provide some comments for those places, that would really speed things up.
This is related to #89.
> Comments for PIOc_write_darray()

- cmake/LibMPI.cmake
- cmake/mpiexec.olcf
Tested on both Eos and Titan, with all unit tests passed.
Fixes #182. If there is a need to create CDash ctest run scripts for OLCF platform as well, we can do it later.
> Allow OLCF users to run ctest via batch scripts or interactive jobs on Eos/Titan

- ctest/runcdash-nwsc-intel.sh
This fixes testing for intel on yellowstone by updating to netcdf-mpi/4.4.1
> update modules for yellowstone intel

- CMakeLists.txt
See #167 for more information. This feature branch has been tested on ANL's Jenkins server to generate nightly code coverage reports.
> Adding a new CMake option to support code coverage

- src/clib/pio_msg.c
needed different indexes and tags in the create_intercomm call in init. Tested on Yellowstone and all async tests pass with this change on that machine. Tested on Laramie and all async tests pass on that machine. The tag was really the key.
@edhartnett Please take a look at these changes. The Laramie test cluster wanted some changes to the MPI_Intercomm_create call to get it to work. I changed the tag to be a single value (rather than all different), and specified the root index of the cmp communicator in a way that, I think, will work better if there is more than one comp component.
> Changes to fix Intercomm_create on Laramie

- src/clib/pio_file.c
- tests/unit/test_file.c
Seeking to add to the test coverage, I found a bug in PIOc_open().
Unlike PIOc_openfile(), PIOc_open() is a copy of the nc_open() function prototype. It passes in a mode parameter, instead of an iotype. It was added for netCDF integration and is not used by any existing PIO users.
The mode is more versatile, because there are more available modes than are expressed in iotypes currently. It also irons out a major issue in the upcoming netCDF integration. (There is no intention of taking PIOc_openfile() away.)
However there was a bug in PIOc_open() in the way I was determining the iotype for netCDF-4 parallel cases, which resulted in using netCDF-4 serial instead.
So on the very first line I tried to increase test coverage, I found a bug. What a great reminder how important it is to have …
> fixed bug in PIOc_open()

- doc/source/code_style.txt
- src/clib/pio_getput_int.c
- src/clib/pio_nc4.c
- tests/unit/test_nc4.c
Fixes #130.
Now the C library builds without warnings. I have added a section to the code style document indicating that no code with warnings will be checked into the C library.
I also have discovered that I didn't have the correct .emacs settings for whitespace on my new machine, which may account for the continuing whitespace issues I keep finding. What I now have, and what we should all have, is:
```
; Set the style for C programming.
(setq c-default-style "linux"
c-basic-offset 4)
(setq-default indent-tabs-mode nil)
```
> Fix compiler warnings in pio_nc4.c

- tests/unit/README
- tests/unit/pio_tests.h
- tests/unit/test_async_2comp.c
- tests/unit/test_async_3proc.c
- tests/unit/test_async_4proc.c
- tests/unit/test_async_simple.c
- tests/unit/test_common.c
- tests/unit/test_darray.c
- tests/unit/test_darray_async.c
- tests/unit/test_file.c
- tests/unit/test_intercomm2.c
- tests/unit/test_iosystem2.c
- tests/unit/test_iosystem2_simple.c
- tests/unit/test_iosystem2_simple2.c
- tests/unit/test_iosystem3.c
- tests/unit/test_iosystem3_simple.c
- tests/unit/test_iosystem3_simple2.c
- tests/unit/test_names.c
- tests/unit/test_nc4.c
- tests/unit/test_spmd.c
Fixes #223.
This PR has test code changes only - no library code.
The C tests were not freeing the test communicator at the end of the test. Now they do.
> now freeing test_comm communicator in C tests

- tests/unit/pio_tests.h
- tests/unit/test_common.c
- tests/unit/test_names.c
- tests/unit/test_nc4.c
Fixes #220.
Only test code changes in the PR.
These tests were made to run on exactly 4 tasks, so are failing when run with 1 task.
I have changed test_names and test_nc4 so that they can run on any number of tasks between 1 and 4. This should cause them to pass on cdash tonight.
Once they do, I will apply these changes to other tests that should be running under MPI_SERIAL but currently are not.
> Change 2 C tests so they work with 1 to 4 tasks, and will pass under MPI_SERIAL

- src/clib/pio_msg.c
- src/clib/pio_nc4.c
- src/clib/pioc_support.c
- tests/unit/test_nc4.c
Fixes #106.
The special netCDF-4 optimization functions were not working or tested with async. Now they are.
Setting the error handler is still not working with async. I will handle that in a separate PR.
> Added async handling of nc4 functions, plus testing

- src/clib/pio_rearrange.c
This is part of #225.
I was working with this code with darrays and noticed a bunch of MPI functions calls where the return value was not being checked. This PR fixes that in accordance with the discussion of MPI errors in #225.
These changes pass all tests.
> Check return values for all MPI library calls in pio_rearrange.c

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_nc.c
- src/clib/pioc.c
- src/clib/pioc_sc.c
- src/clib/pioc_support.c
Fixes #234.
This removes the unneeded "const"s before scalar paramters in the C function prototypes.
For example: 
`PIOc_closefile(const int ncid)`
becomes
`PIOc_closefile(int ncid)`
As far a C compilers are concerned this is not an important change, and it should go unnoticed everywhere.
> removed const from scalar parameters in function prototypes

- src/clib/pio_darray_int.c
Fixes #257. Part of #225.
Added return code checking to MPI calls that didn't have it in pio_darray_int.c.
> Return checking for MPI functions in pio_darray_int.c

- CMakeLists.txt
- cmake/LibMPI.cmake
This feature branch has been tested on ANL's Jenkins server to generate nightly valgrind check reports. Some memory leaks are confirmed in #245.
> Adding a new CMake option to perform valgrind memory check

- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
Working on #238, need to clear #225.
In this PR I add pio_err(), the function that will handled errors in the PIO library. It checks with the file and iosystem error handlers (in that order) to decide what to do with the error.
Also I note that setting the file error_handler actually just changes the iosystem error handler for that file, which is not right. So I have added an error_handler field to file_desc_t, it is initialized to 0 when a new file_desc_t is created.
> adding pio_err() function to handle PIO errors

- doc/source/contributing_code.txt
- src/clib/pio_file.c
A very simple PR to take us through our first merge with the develop branch.
This PR uses the pio_err() function in the rest of pio_file.c. (See issue #225.)
I have also started to document our merge procedure, which is being discussed in email and other place. Please take a look at what I have put in the contributions document.
> fixed returns in pio_file.c to use pio_err(), working out code merge procedure

- src/clib/pio_darray_int.c
- src/clib/pio_file.c
- src/clib/pio_get_nc.c
- src/clib/pio_getput_int.c
- src/clib/pio_internal.h
- src/clib/pio_nc.c
- src/clib/pio_nc4.c
- src/clib/pio_put_nc.c
- src/clib/pio_varm.c
- src/clib/pioc_support.c
Here are changes to use the new check_netcdf() function, and remove the old one.
The new function, as you may recall, accepts the iosystem_desc_t for those cases where we have an ios but not a file to decide what error handling to use.
> Ejh check netcdf2

- ctest/runcdash-nersc-cray.sh
- ctest/runcdash-nersc-intel.sh
- ctest/runctest-nersc.sh
Still having timeout problems on cori but this is a step in the right direction.
Something is currently wrong with the netcdf 4.4.1 and hdf5 1.10.0 modules, this has
been reported to nersc support.
> Update nersc cdash

- tests/general/util/pio_tf_f90gen.pl
If the test driver fails make sure that we report an error. Without
this fix failures in the test driver is not signaled as an error.
Fixes Issue #284
> Make sure a test driver fail is signaled as a fail

- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
There is one case (at least) where there is an ios but not a file pointer, and that is in deletefile.
This PR adds a check_mpi2() which can be used in those cases to make sure the correct error handler is used.
> added check_mpi that accepts ios, for use in deletefile function

- CMakeLists.txt
- examples/c/CMakeLists.txt
- tests/CMakeLists.txt
This adds the C examples as extra tests.
It also allows users to disable building the examples. By default examples are built and run as tests.
Previously they were built, but not run as tests.
Fixes #322.
> added PIO_ENABLE_EXAMPLES, also now run C examples as extra tests

- examples/c/example1.c
example1 did not build in non-pnetcdf builds.
In this PR it is made to build correctly for all the different build possibilities.
This is part of #293.
I will merge this to develop for testing.
> made example1 responsive to different build variations

- src/clib/pioc_support.c
Some memory leaks are reported by both Valgrind and LeakSanitizer on pio_decomp_fillval test. In PIOc_freedecomp(), we should clean gsize array and fillregion linked list in io_desc. Before it goes to master, this fix will be merged to the develop branch to be tested by some nightly builds. Fixes #305.
> Fixing some memory leaks on pio_decomp_fillval test

- tests/unit/test_iosystem2.c
because of the following MPI warning message.
In direct memory block for handle type COMM, 1 handles are still allocated
...
> free MPI communicator newcomm

- src/clib/pio_nc.c
Fixes #333.
Only a small change was needed to make classic-only builds work...
I will merge this into develop for testing.
> fixed classic-only build

- src/clib/pioc_support.c
Fixes #274.
I can't get mpiserial builds working on my test machine, so let's just try this on develop with cdash testing.
> removed call to mpi-serial abort() function

- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_iosystem3.c
- tests/cunit/test_nc4.c
- tests/general/util/pio_tutil.F90
Fixes #330.
Fixes #268.
Part of #238, part of #225.
Setting the iosystem error handler was not working (even for non-async cases). This was tested in test_nc4, where I delete a file, and then try to reopen it, only to get an error code.
This was causing an abort, because it was not accepting my setting of the iosystem error handler to RETURN. (Which I need for this test to work.)
I have introduced new functions PIOc_set_file_error() and PIOc_set_iosystem_error() because I need all API functions to return an error code on failure, and the existing PIOc_Set_File_Error_Handling() and PIOc_Set_IOSystem_Error_Handling() return the previous setting and have no way to return errors.
The old functions are still there and still supported, but I guess they should be removed, and the new ones used …
> fix setting of iosystem error handler with no file_desc_t present for non-async cases

- src/clib/pio_spmd.c
- src/clib/pioc.c
- src/gptl/gptl.c
- tests/cunit/test_darray.c
Fixes #232.
Part of #225.
In this PR I add checking to an MPI function call. Also I remove CheckMPIReturn() because it has now been replaced with check_mpi().
I have merged this into develop for testing.
> error handling for MPI call

- tests/cunit/test_darray.c
- tests/cunit/test_file.c
- tests/cunit/test_names.c
- tests/cunit/test_nc4.c
A few C unit tests (test_darray, test_file, test_names, test_nc4) have memory leaks due to missing necessary PIOc_finalize() calls. This fix will be merged to the develop branch to be tested by some nightly builds.
> Fixing memory leaks on several C unit tests

- src/gptl/gptl.c
Got the following compile-time warning messages.
src/gptl/gptl.c: In function 'merge_thread_data':
src/gptl/gptl.c:2578: warning: passing argument 4 of 'qsort' from incompatible pointer type
/usr/include/stdlib.h:761: note: expected '__compar_fn_t' but argument is of type 'int (*)(const char **, const char **)'
src/gptl/gptl.c:2625: warning: passing argument 4 of 'qsort' from incompatible pointer type
/usr/include/stdlib.h:761: note: expected '__compar_fn_t' but argument is of type 'int (*)(const char **, const char **)'
src/gptl/gptl.c:2648: warning: passing argument 4 of 'qsort' from incompatible pointer type
/usr/include/stdlib.h:761: note: expected '__compar_fn_t' but argument is of type 'int (*)(const char **, const char **)'
src/gptl/gptl.c: In function 'collect_data': …
> silence compile warnings caused by the use of qsort

- ctest/runcdash-nwsc-gnu.sh
Fixes issues with tests failing in cdash. netcdf 4.3.3.1 has known problems, updated to netcdf 4.4.1
also updated gnu to 6.1.0 and pnetcdf to 1.7.0.
Already merged to develop.
> update compiler and netcdf libraries

- tests/unit/driver.F90
- tests/unit/global_vars.F90
The old fortran unit test used hardcoded lengths for strings used
to retrieve pio error messages. Now using pio_max_name instead.
See Issue #319
> Remove hardcoded string lens in unit test

- src/clib/pio_msg.c
Part of #245.
Fix a leak of a group that was created but never freed.
> fixed MPI group leak in pio_msg.c

- src/clib/pio_file.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
Fixes #357.
Fixes #356.
This PR fixes two leaks and an incorrect return in a test. Thanks to @dqwu for pointing these out.
I will merge this to develop for testing.
> fixed leaks if createfile or openfile fails, fix test problem

- src/clib/CMakeLists.txt
- src/clib/pioc_support.c
Fixes #355.
This has been merged to develop for testing.
> turn on nc_set_log_level if PIOc_set_log_level with level > 3 is called

- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
Fixes #373.
Also changed parameter to be lower-case everywhere. In C it is a very strong convention that defined macro constants (like _NETCDF4) are all upper-case, and variables are lower-case. Sticking with C convention makes our code more readable and easier to maintain, for us and others.
> updated docs with more info on iobuf parameter

- doc/source/mach_walkthrough.txt
- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_iosystem3.c
- tests/cunit/test_pioc.c
Based on discussions with Jim I realized that the file-based error handling I was using was not correct.
Here's the fixes to remove it and make the error handling work as expected.
> Remove incorrect file-level error handling

- src/clib/pio_darray_int.c
Since we are calling this on the last iosystem on each task and these iosystems do not necessarily reflect a common communicator we cannot use collective calls.
Fixes #118
> this cannot be collective

- src/clib/pio_darray.c
Fixes #410 
If any iotask has holegridsize > 0 then all must enter this code.
> fix an error in knowing if you need to fill holes

- src/clib/pio_internal.h
- src/clib/pio_rearrange.c
- src/clib/pio_spmd.c
- src/clib/pioc_support.c
We had a workaround for MPI_DATATYPE_NULL for OPEN_MPI in pio_spmd.c, it turns out that SGI's MPT also needs this workaround.  So I added a PIO_DATATYPE_NULL macro and moved the definition to pio_internal.h OPEN_MPI and MPT_VERSION are macros defined in the respective MPI libraries so no further changes to the build are required.
> add PIO_DATATYPE_NULL with switch depending on MPI variety

- src/clib/pioc.c
- src/clib/pioc_support.c
Saving of the decomp can now be achieved by calling PIOc_write_decomp().
The code removed in this PR is left over from the environment variable method of saving decomps.
Fixes #442.
> removed unneeded code for saving decomp

- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
- tests/cunit/test_pioc_putget.c
- tests/cunit/test_shared.c
In order to test checking for invalid parameters, I need to be able to change the default error handling. This PR includes the introduction of constant macro PIO_DEFAULT. When passed as the iosysid into int PIOc_set_iosystem_error_handling(), this will change the default error handling for the library. (That is, the error handling that is used to initialize io systems, and when an io system cannot be located at the time of error.)
Also added a bunch of tests to test_pioc.c for invalid parameter handling. Turned on some old test code I wrote but could not use before.
Fixes #412.
Fixes #458.
Fixes #421.
Fixes #422.
This is all part of #205.
> allow changes to default error handler, some tests for invalid parameters

- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_file.c
- src/clib/pio_get_nc.c
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- src/clib/pio_put_nc.c
- src/clib/pio_varm.c
- src/clib/pioc.c
- src/clib/pioc_sc.c
- src/clib/pioc_support.c
- tests/cunit/test_common.c
- tests/cunit/test_intercomm2.c
- tests/cunit/test_iosystem2_simple.c
More error handling cleanup and additional tests. Moved PIOc_set_blocksize to a file where it will be included in public documentation; also added a test for it. Removed the now unneeded function iotype_error().
Fixes #462.
Fixes #454.
Fixes #452.
Fixes #449.
Fixes #446.
> More error handling cleanup, moved PIOc_set_blocksize

- src/clib/pio.h
- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc_putget.c
Added tests for attribute writes/reads of all types.
Also changed check_netcdf2() so that the netCDF error message is logged. (It is only printed if PIO_ERROR_INTERNAL is being used and there is an abort.)
Also re-ordered the attribute functions in pio.h.
Fixes #431.
I will merge with develop for testing.
> attribute read/write tests

- src/clib/pio_msg.c
- src/clib/pioc_support.c
Ran with -Wall and fixed warnings in two files, including pio_msg.c.
Mostly just removed unused vars. Thanks to @dqwu for pointing these out.
I will fix other files as well in future PRs.
Part of #485.
> removed unused vars and fixed other warnings

- tests/unit/ncdf_tests.F90
> Fix return statements in wrong places for netCDF-4/HDF5 iotype in ncdf_tests.F90

- tests/cunit/test_intercomm2.c
This updated test is part of #498 (need more tests).
If the fix for #377 (see PR #378) is reverted, this test will fail due to incorrect num_elem calculated (manually tested). Therefore, it is now a regression test for that fix.
> More combinations of start/count for checking the file in test_intercomm2

- src/clib/pio_internal.h
- src/clib/pio_nc.c
- src/clib/pio_rearrange.c
- src/clib/pioc.c
- tests/cunit/test_intercomm2.c
- tests/cunit/test_iosystem2.c
- tests/cunit/test_iosystem3.c
- tests/cunit/test_pioc.c
Fixes #507.
Fixes #506.
Fixes #505.
Part of #441.
Fixes #510.
Fixes #430.
Part of #205 (of course).
Filling in lots of missing test cases, mostly checking that invalid parameters are properly rejected.
PIOc_set_hint() was not actually working because the info object was not always present. That's fixed in this PR.
Also fixed a few cases of bad error handling. We usually don't want to call piodie(). Instead call pio_err() which checks the error handler and only dies if it should.
> more tests

- tests/general/pio_rearr_opts.F90.in
The communicator used was dup'ed every time (to be used in
PIO init) inside the loop but only freed once (outside the
loop). Moving the free for the dup comm inside the loop.
Fixes #520
> Fix mem leak in rearr opts test

- src/clib/pio_get_nc.c
- src/clib/pio_getput_int.c
- src/clib/pio_internal.h
- src/clib/pio_msg.c
- src/clib/pio_nc.c
- src/clib/pio_put_nc.c
- tests/cunit/test_pioc.c
- tests/cunit/test_pioc_putget.c
Fixes #555.
Fixes #550.
Fixes #528.
Fixes #420.
Fixes #557.
In netCDF the handling of long ints was a momentary lapse in judgement. The netcdf.h file assumes that long ints are the same as ints. (NC_INT = NC_LONG). However, that is no longer true.
To handle this I needed to add an internal type, PIO_LONG_INTERNAL. This type may not be used to create variables or attributes, but is used internally when one of the _long() functions are called, to indicated that the buffer is allocated in terms of long int (whatever that size is on that machine).
Also added tests relating to these changes.
I will merge to develop after my local jenkins builds all it's variants on my branch on my machine.
> fixed _long() problems with new internal type

- src/clib/pio_file.c
- src/clib/pio_rearrange.c
- src/clib/pioc_support.c
The retry portion of openfile_retry was not working because file->do_io needed to be reset to the 
correct serial netcdf value.     There are several whitespace changes in this PR indicating that someone is still committing files with white space additions.
> fix issue in openfile_retry

- tests/cunit/test_pioc_putget.c
Fixes #563.
Part of #205.
This test was written but was not being run due to an incorrect constant in the test program. Now the test runs.
No library changes in this PR - just test code.
> turned on test for PIOc_put/get_vars()

- tests/cunit/CMakeLists.txt
- tests/cunit/test_pioc_more.c
- tests/cunit/test_shared.c
More tests relating to fill values.
Added a new test file test_pioc_more.c, for this and other new tests.
Fill values are not working as expected for pnetcdf. I have a support ticket open with the pnetcdf team about that. For now, pnetcdf is skipped for most fill value testing.
For variety of testing I changed around the start/count values so that I am not using the same combinations used in other tests (part of #498).
Fixes #578.
Part of #572.
Part of #83.
Only test code in this PR - no library changes.
I will merge to develop when my branch testing is complete.
> more tests for fill values in all types

- src/flib/piolib_mod.F90
Making sure that we set the log level in the C library when user
sets the debug level via the Fortran interface.
Fixes #576
> Set log level when setting debug level

- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/test_pioc_more.c
Fixes #568.
Turns on NOFILL for all files created with PIOc_createfile().
Does NOT change fill setting for files created with PIOc_create().
> change default fill mode for PIOc_createfile()

- src/clib/pio_darray_int.c
- src/clib/pio_file.c
- src/clib/pio_getput_int.c
- src/clib/pio_nc.c
- src/clib/pio_varm.c
- src/clib/pioc.c
- src/clib/pioc_support.c
Since the build will not work without at least netCDF classic, these ifdefs were not serving any purpose. The build will not work without netCDF (i.e. pnetcdf-only) without some effort.
I think it's reasonable to expect that any HPC user of PIO is already going to have at least netCDF classic on their system.
Fixes #597.
> Remove unneeded #ifdefs

- tests/cunit/CMakeLists.txt
- tests/cunit/test_pioc_unlim.c
Fixes #441.
Test code only in this PR.
I added a new C test, test_pioc_unlim.c, for tests of decompotion/darray/etc which involve an unlimited dimension. (Existing tests don't have unlimited dim).
This allowed testing of the PIOc_setframe() and PIOc_advanceframe(), and that's what this PR does, but future PRs will add aditional tests to test_pioc_unlim.c.
> Added test for cases where unlimited dimension is in use

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
Added function PIOc_read_nc_decomp() to read netCDF decomp file and initialized iodesc. Plus tests. Fixes #627.
Also more tests for PIOc_write_nc_decomp(). Fixes #654.
> Now read netCDF decomp file and InitDecomp() with values

- doc/source/mach_walkthrough.txt
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pio_rearrange.c
- src/clib/pioc.c
- src/clib/pioc_support.c
In this PR I add return code checking in several places. Remember:
`void functions + programmer laziness = ignored return codes
`
So just return int from all new functions. ;-)
Also changed some functions that were passing whole struct instead of pointer to struct. Using the struct causes the entire contents of the struct to be copied, instead of just a pointer to it. So we need to follow the C convention of always passing pointers to structs, not the structs themselves.
Fixes #679. 
Fixes #678. 
Fixes #676. 
Fixes #677.
Fixes #675.
> return value checking, changing parameters to pointers to struct

- src/clib/pio.h
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/test_darray_3d.c
- tests/cunit/test_decomps.c
- tests/cunit/test_pioc.c
Added cmode param to allow netCDF-4 decomp files. (Fixes #693)
Changed parameter order to match other functions. (Fixes #717)
Add backtrace as an attribute. (Fixes #436)
More tests.
> Changes to read/write netCDF decomp files

- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_file.c
Non-iotasks were calling ncmpi functions and thus returning an invalid file id error.
I have merged to develop for testing
Fixes #719
> fix issue with non iotasks calling flush

- src/clib/pio_darray.c
- tests/cunit/test_darray.c
- tests/general/pio_decomp_tests.F90.in
Allowing user buffers larger than the size expected (as specified in the
IO decomposition) by the current process.
* Fixes a C test that checked for larger user buffers to test for smaller
user buffers
* Adds a new Fortran test that specifies larger user buffers
* Minor doc change
Fixes #577
> Allow user buffers larger than local ndof

- tests/cunit/pio_tests.h
- tests/cunit/test_common.c
- tests/cunit/test_darray.c
- tests/cunit/test_decomps.c
Looking at the code, it seems that the only types that are supported with darray are PIO_INT, PIO_FLOAT, and PIO_DOUBLE.
In this PR I change test_darray.c so that it tests all three types. Only test code changes in this PR.
Future work will include trying out other types. ;-)
Fixes #665.
Part of #205.
> add darray testing for different types

- src/clib/pioc_support.c
When error mode is PIO_BCAST_ERROR we do not want to print error strings returned from netcdf, instead just return the error code to the application.   This is so that expected errors such as variable or dimension not found in a query function do not write error messages to stderr.  
merged to develop
> do not print netcdf errors in PIO_BCAST_ERROR mode

- src/clib/pio_internal.h
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
This is one of several changes that will be necessary before all types, including netCDF-4 types (when available), can be used for darrays.
This change will not affect current users, who are limited to the three currently supported darray types, PIO_INT, PIO_FLOAT, and PIO_DOUBLE.
Fixes #473.
> change malloc_iodesc to handle all types, including netCDF-4 types

- src/clib/pio_darray.c
- tests/cunit/test_darray_1d.c
This PR contains important code changes.
In this PR I change the code in PIOc_write_darray_multi() which copies the fill values to the buffer for both  rearrangers. This code previously only worked for types that were of length 4 and 8.
Now this code will work for all types, instead of just the big 3 (PIO_INT, PIO_FLOAT, and PIO_DOUBLE). ;-)
Fixes #543.
> changed fill value copying to be typeless

- src/clib/pio_nc4.c
- src/clib/pioc.c
For error handling, if we have an ios but no file, we want to use check_mpi2(). This will use the error handler set in the iosystem.
Berfore we had check_mpi2() we just used check_mpi(). In this PR I update a few check_mpi() calls that should be check_mpi2() calls.
Fixes #770.
Fixes #771.
> fixed error handling in a couple of places

- tests/general/CMakeLists.txt
The scenarios tested by 1 proc and 3 proc cases of this test (pio_rearr_opts) 
is also covered by another test (pio_rearr_opts2). Since this test is "heavy",
removing the 1proc and 3proc cases (and retaining the 4 proc case)
for this test.
This change speeds up the testing process without sacrificing coverage.
No code changes.
> Removing long redundant tests

- src/clib/pio_darray_int.c
In this PR are some serious code changes.
I changed to typeless netCDF gets and puts in pio_darray_int.c.
These will work for the three currently-supported types (PIO_INT, PIO_FLOAT, and PIO_DOUBLE), but will also work for other types.
Fixes #674.
> fixed type-dependant netcdf calls

- src/clib/pio_spmd.c
- tests/general/pio_rearr_opts2.F90.in
Change max requests setting in PIO2 to reflect the settings
in PIO1. Also handling the case where user specifies unlimited
number of requests.
Also adding a test to cover the case where user sets max requests = 1
Fixes #779
> Change max requests setting in flow control code

- src/clib/pio.h
- src/clib/pioc.c
- tests/cunit/test_darray_3d.c
Added a new version of init decomp, but with 0 based array.
Fixes #414.
> version if init_decomp with 0-based arrays

- src/clib/pioc.c
Minor error handling fix. This function cannot return an error so must die.
Fixes #795.
> fixed some error handling

- src/clib/pio.h
- src/clib/pioc.c
- tests/cunit/test_async_4proc.c
The API to PIOc_Init_Async() is unclear and poorly documented.
This PR introduces new function PIOc_init_async(). Yes the name is confusing bu PIOc_Init_Async() will be taken out in a future PR pretty shortly.
This is the same code, but now the API makes a more clear separation between IO and computation components.
I'm just putting this up to do the change in smaller batches, and to give people time to comment on the changed API before I change it everywhere in the library and tests. With this PR one of the async tests has been converted to the new PIOc_init_async().
Fixes #402.
> new, less confusing PIOc_init_async() API

- src/clib/pio.h
- src/clib/pio_darray.c
Some important code changes in this PR, so look closely.
After recent simplifications in the code it became clear that the setting of wmb->ioid to -ioid in the case of non-record vars was never used anywhere. So I was able to simply remove it.
Fixes #713.
> removed -ioid from PIOc_write_darray()

- src/clib/pio_internal.h
- src/clib/pioc.c
- src/clib/pioc_sc.c
- src/clib/pioc_support.c
- tests/cunit/test_spmd.c
In this PR I modify the find_mpi_type() internal function to also provide the size of the type.  
This is used in CalcStartandCount() and will be used in other places. Doing this in the find_mpi_type() function will allow us to support all types with darrays.
I also change CalcStartandCount() to return an error code, and change one of the param names to make it clear that it is a PIO type, not an MPI type.
Fixes #791.
Fixes #811.
Fixes #810.
Part of #809.
Part of #813.
> change type size determination

- src/clib/pio_darray.c
Fixes #849. See issue for discussion.
Part of #89.
> cleaned up some rearranger code

- src/clib/pio.h
- src/clib/pio_internal.h
- src/clib/pio_rearrange.c
- tests/cunit/test_spmd.c
Starting to add tests for create_mpI_datatypes() function.
Removed an unused param from the function.
Please help me turn some of the ??? into comments.
Fixes #854.
Part of #855.
Part of #205.
Part of #89.
> Start of testing, removed unneeded param from create_mpi_datatypes()

- ctest/CTestEnvironment-anlworkstation.cmake
This allows CTest scripts for ANL workstations to optionally turn on PIO_USE_MALLOC.
> Update CTestEnvironment-anlworkstation.cmake on PIO_USE_MALLOC

- src/clib/pio_darray.c
Fixes #885 
Fixes #888
Flush pnetcdf output buffer before attempting to write a new record.  Allocate a token iobuf on all iotasks so that this flush is collective.
> Fix malloc mem issue

- src/clib/pio_darray.c
More changes are needed for openmpi, but here is one of them. Stop treating MPI_Datatype as an int.
Part of #897.
> Change case to if statement (needed for openmpi)

- tests/cunit/test_darray_1d.c
- tests/cunit/test_pioc.c
Part of #897.
Part of #898.
Part of #886.
> clean up some MPI_Datatype issues in tests for openmpi builds

- src/clib/pio.h
- src/clib/pioc.c
- tests/cunit/test_async_3proc.c
- tests/cunit/test_async_4proc.c
- tests/cunit/test_async_simple.c
- tests/cunit/test_darray_3d.c
- tests/cunit/test_decomp_uneven.c
- tests/cunit/test_intercomm2.c
- tests/cunit/test_pioc.c
- tests/cunit/test_shared.c
One thing that is preventing some of the decompositon tests from working in async is that async does not handle rearrangers (at all!). So when the code needs a rearranger, it can't find one.
This PR adds the rearranger parameter to the init_async call to get a default rearranger.
Fixes #908.
Fixes #907.
Part of #89.
> adding rearranger parameter to init_async function

- examples/c/example1.c
- src/clib/pio_rearrange.c
There is a warning from openmpi about this (see #897); we are using a deprecated version of the MPI_Type_hvector(). Instead we should be using MPI_Type_create_hvector(), which has the exact same arguments, just a different name. From the [MPI docs](http://mpi-forum.org/docs/mpi-2.2/mpi22-report/node327.htm):
```
The following function is deprecated and is superseded by MPI_TYPE_CREATE_HVECTOR in MPI-2.0. 
The language independent definition and the C binding of the deprecated function is the same as of the 
new function, except of the function name. Only the Fortran language binding is different.
MPI_TYPE_HVECTOR( count, blocklength, stride, oldtype, newtype)
```
Similarly:
```
The following function is deprecated and is superseded by MPI_COMM_SET_ERRHANDLER in MPI-2.0. 
The language …
```
> fixing openmpi warnings

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_lists.c
Now keep track of the fill value info for each var in the varinfo array in the file struct.
The first time a darray_write is called, if this info is not present in the file varinfo array, it is obtained and stored there. This way, the metadata calls only take place once, no matter how many darray calls take place.
This fill value information will be used in the darray functions to ensure that the correct fill value was passed. Type info will be used to allow types of different sizes to share the same iodesc.
Part of #83.
Part of #690.
Part of #934.
> keeping fill and type info about vars used in darrays

- tests/cunit/CMakeLists.txt
Just increased timeout times. As I add to tests, they take longer. test_darray_multivar is now timing out on my Jenkins server.
> changed timeout times

- src/clib/pio.h
- src/clib/pio_rearrange.c
- src/clib/pioc.c
- tests/cunit/test_rearr.c
For non-async cases, the number of computation tasks == the number of tasks in the union_comm. So ios->num_comptasks has been used in the code as the size of the union comm. This size is used for the length of 6 arrays that are passed to pio_swapm() (sendcounts, sdispls, etc.).
But with async, the union_comm has a different size.
I have added a field num_uniontasks. For non-async cases it is the same as num_comptasks.
In this PR I have changes to ensure that pio_swapm() calls on the union_comm use arrays of length ios->num_uniontasks. This fixes a problem for async, but has no effect on non-async cases.
Fixes #980.
Part of #981.
Part of #89.
> Fixes to code to allow it to work with async; no effect on non-async cases

- pio/pio.F90
- pio/piolib_mod.F90
Porting pio_set_rearr_opts() interface from PIO2 to PIO1.
Fixes #989
> Add pio_set_rearr_opts to pio1

- ctest/runcdash-cgd-gnu-openmpi.sh
- ctest/runctest-cgd.sh
This branch adds a openmpi build to the cdash tests, it uses gnu 5.4.0 and openmpi 2.0.2 
currently the build completes without error but a number of tests are failing.   
> add gnu openmpi test for hobart

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/CMakeLists.txt
- tests/cunit/test_darray_multivar2.c
Part of #973.
This PR does not change any existing functionality. I moved some of the code blocks in pio_write_darray_multi_nc_serial() to internal helper functions. I also changed the name of the function to write_darray_multi_serial() and cleaned up some of the parameters.
Also added a test (test_darray_multivar2.c) with the test that demonstrates the issue. (Test is commented out so CI won't fail).
This is in preparation for solving the #973 issue for serial writes.
> Changes to darray code -  moved some code blocks to internal functions

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_nc.c
- tests/cunit/test_darray_multivar2.c
- tests/cunit/test_pioc.c
Fixes #973.
Part of #1004.
Now mixing record and non-record variables in darray operations works again.
I added a field recordvar to the wmb. Along with the ioid, this is used to find a multi-buffer for a darray operation. As used to occur with the negative ioid, the non-record vars now have their own multi-buffer.
I will also add a ticket to further strengthen testing for this feature.
> handle record and non-record vars in darray writes

- tests/general/pio_decomp_frame_tests.F90.in
The new test reuses the same 3d decomp to write out a 3d and a
4d (one frame at a time) var.
This test is related to the Issue #973 and fails before PR #1003 was
merged to master.
> Adding a fortran test that reuses decomp btw 3d and 4d vars

- pio/CMakeLists.txt
- pio/pionfput_mod.F90.in
Fixes an issue with pio1 determining if netcdf4 is available and removes a debug print statement.
Porting changes from ESMCI/cime#1425 to PIO1 branch.
> Fix PIO1 NetCDF4P support

- src/clib/pio_darray_int.c
There are cases where we call ncmpi_inq_buffer_usage before we have defined a buffer, these result in error NC_ENULLABUF from pnetcdf - ignore this error.  Tested in cesm, merged to develop.
> allow error NC_ENULLABUF from netcddf when checking buffer status

- tests/general/util/pio_tutil.F90
The log level for the fortran tests was inadvertently set to 3 in
45471c61f6af280bd97c3471e3d9444f8e04c507
By default the log level should be 0
> Reset fortran test log level to 0

- tests/cunit/test_darray_async.c
Only new test code in this PR, no library modifications.
With this PR, test_darray_async now runs its test for all data types. Previously only PIO_FLOAT was tested.
Fixes #1018.
Part of #89.
Part of #388.
> Expanded testing for darray writes with async

- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
Changed internal function name and parameters of pio_write_darray_multi_nc() to match recent changes in serial version of this function.
No big functional changes, I just shortened the parameter list by passing pointer to iodesc, and fill parameter to indicate whether this is fill or data.
Also added the fndims parameter. Due to async, PIOc_* functions may not be called in these internal functions.
These changes are in support of getting async darray writes working for parallel iotypes.
Fixes #1022.
Part of #89.
> changed some parameters to internal darray function

- tests/cunit/test_darray_async.c
- tests/cunit/test_darray_async_many.c
- tests/cunit/test_darray_async_simple.c
Now all IOTYPES are working with async darray writes.
Fixes #1030.
Part of #388.
Part of #89.
> Turning on async darray tests for pnetcdf

- scripts/prune_decomps.pl
The prune decomp script has the following changes,
* Refactored to be more modular etc
* Has help/option message, debug messages
* New options (--exe option to specify executable, --verbose option for verbose log msgs)
* Fixed a bug that resulted in dup files not being deleted
* Some fixes that would improve performance
> Fix the prune_decomp script to delete dup files

- doc/source/contributing_code.txt
Fixes #1055.
If there are no objections, we can start adding author tags as we work on the code.
> added instructions for author tags

- src/clib/pio.h
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- tests/cunit/test_spmd.c
The current code uses an array of NC_MAX_VAR length to hold the var metadata for each file.
This is a poor choice for several reasons, including:
* wastes lots of memory
* initialing values that are never used
So I am switching to lists of var_desc_t instead of arrays. This PR includes the list handling functions, and their tests. In a future PR I will change the code to use these lists.
Part of #1051.
Part of #1052.
Part of #544.
> New functions for handling varlist

- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc_unlim.c
PIO can only tolerate one unlimited dim per variable.
NetCDF-4 files are now checked (when opened) to make sure they meet this requirement. Also def_var is changed so that invalid vars cannot be defined with PIO.
Fixes #214.
> Check that netCDF-4 files created/opened with PIO don't misuse unlimited dims

- src/clib/pio_lists.c
- src/clib/pio_nc.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
In this PR I use the new var_desc_t linked list to improve error handling in PIOc_setframe() and PIOc_advanceframe().
Fixes #1083.
Part of #1052.
Part of #1051.
Part of #544.
> advanceframe and setframe now use new var_desc list

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_file.c
- src/clib/pio_getput_int.c
- src/clib/pio_lists.c
- src/clib/pio_nc.c
- src/clib/pio_varm.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc_unlim.c
In this PR I finish changing the var_desc_t information from an array of NC_MAX_VAR, into a linked list.
Fixes #1086.
Fixes #1085.
Fixes #1052.
Fixes #544.
These changes are needed to support proper fill value handling, as in #729, #768, #1037, and #83.
> Final work on var_desc_t linked list, clean up if intermediate efforts

- src/clib/pio_darray.c
- tests/cunit/CMakeLists.txt
- tests/cunit/test_darray_multivar3.c
See #1037 for discussion.
This PR adds a test that demonstrates problem. Code in test that causes error is commented out so that CI can continue to pass.
I have merged with develop for testing. Current uses of PIO should be worried about this bug, I think. If you mix types in your iodesc, you may have problems in your output data.
Short-term fix is to disable writing in an iodesc defined for another type.
Long-term fix is to move the type information out of the decomposition, which would be type-neutral. The code needs to be modified to use the correct fill values regardless of the decomposition. But this is a fair amount of work.
> Added test which demonstrates some problems with fill values and mixed types in iodesc

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/cunit/test_darray_multivar3.c
- tests/cunit/test_spmd.c
Fixes #1037.
Fixes #1034.
Now return error if user calls PIOc_write_darray() or PIOc_write_darray_multi() for vars with type that does not match decomposition type.
Someday we hope to relax this restriction. (See #934).
> darray write functions now check for correct type

- tests/cunit/test_darray_async.c
> turned call to PIOc_write_nc_decomp() back on

- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
- tests/cunit/test_pioc_fill.c
Turns out the only reason we were remembering the mode from create/open was to know if the file was writable.
I have removed mode from file_desc_t and added field writable instead.
Fixes #1119.
Fixes #1113.
> Added writable, removed mode flag from file_desc_t, fixed PIOc_inq_var_fill()

- configure.ac
set _PNETCDF based on whether parallel-netcdf library is found, also added comments.
Part of #1135.
I will merge to develop for testing. Should be no impact on CMake builds.
> set _PNETCDF based on whether parallel-netcdf library is found

- src/clib/pioc_support.c
- tests/cunit/test_pioc.c
- tests/cunit/test_pioc_unlim.c
In this PR I turn off a printf statement in the library that was printing error messages.
The printing of PIO error messages must be left to the caller. In many cases, (such as my tests) there will be returned errors which do not need or want an error message printed, because the non-zero return code is expected, or handled by the caller. In such cases, error messages will confuse the user and make them think something is wrong, when it isn't.
Fixes #1151.
Part of #1135.
> turned off printf output from library during tests

- tests/cunit/test_darray_multivar.c
- tests/cunit/test_darray_multivar3.c
- tests/cunit/test_pioc.c
fixed tests that were providing incorrect fill value for write_darray()
Fixes #1164.
Part of #83.
> fixed tests that were providing incorrect fill value for write_darray()

- src/clib/pioc_support.c
- tests/cunit/test_async_multicomp.c
Part of #1134.
Part of #1190.
Part of #403.
Fixed the assignment of ncid for async case with 2 computation components, each creating a different file.
This test produces a simple test file - a more complex test case is coming in a future PR.
When I include the change in openfile, this causes one of the later fortran tests to fail. I will check in what is working, and work on the fortran test in a future PR.
> Simple test for multiple computation components with async

- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/test_iosystem3.c
The necessary variable metadata was not being bcast to all the correct tasks when a file is opened. (See #1205).
In this PR I rearrange the openfile code, so that all tasks end up with the metadata. This is needed before more advanced async tests can work.
Fixes #1205.
Part of #1194.
Part of #89.
> Fix problem with openfile and variable metadata

- CMakeLists.txt
- cmake_config.h.in
- configure.ac
- src/clib/pio_darray.c
- tests/cunit/test_async_multi2.c
- tests/cunit/test_iosystem2_simple.c
- tests/cunit/test_iosystem3.c
Fixes #1203.
Fixes #1213.
Raised buffer size to 100 MB.
Added ability to override in CMake/autotools build systems.
> added PIO_BUFFER_SIZE to build systems

- src/clib/pioc_support.c
The type for mpi_type in the routines inq_file_metadata and PIOc_openfile_retry
in pioc_support.c is int but should be MPI_Datatype because mpi_type is used in
calls to, e.g., MPI_Type_size (https://www.open-mpi.org/doc/v2.0/man3/MPI_Type_size.3.php).
In most implementations of MPI, the size of MPI_Datatype is the same as the size
of int, but in some versions of OpenMPI, MPI_Datatype actually has a size of 8.
This leads to memory errors and segfaults in PIO.
> Partial fix for incorrect type of 'mpi_type' in pioc_support.c

- src/clib/pio_darray.c
the limit of data_size < INT_MAX is due to a bug in ROMIO which limits
the size of contiguous data to INT_MAX, a fix has been proposed in
https://github.com/pmodels/mpich/pull/2888
merged to develop
> limit to 2GiB due to romio bug

- ctest/runcdash-nwscla-intel.sh
- src/clib/pio_getput_int.c
- src/clib/pio_msg.c
- src/clib/pio_nc4.c
- src/flib/pio_types.F90
pnetcdf 1.9.0 sets NC_MAX_VARS and NC_MAX_DIMS to MAX_INT to indicate they should no longer be used.
> dont use NC_MAX values

- src/flib/CMakeLists.txt
The Cray Fortran compiler by default write module files in
all uppercase. The "-ef" flag tells it to write them as
lowercase. This means the install phase can file the module
files to install.
This fixes #1249.
> Adding Cray Fortran specific flags.

- ctest/runcdash-nwscla-intel.sh
Module order was incorrect for cheyenne.  Merged to develop.
> reorder modules

- src/clib/pio_darray_int.c
- src/clib/pio_getput_int.c
- src/clib/pio_msg.c
- src/clib/pio_varm.c
- src/clib/pioc_support.c
Fixes #1260.
Mostly moving pnetcdf-only vars into the pnetcdf blocks of code that use them.
> fixed compiler warnings

- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_msg.c
- src/clib/pio_nc.c
- src/clib/pioc.c
- tests/cunit/test_darray_1d.c
- tests/cunit/test_darray_2sync.c
Some fixes to adjust fill value behavior to match netCDF library changes.
C tests now all pass with newer netCDF versions. One fortran test continues to fail with netcdf versions after 4.4.1.1.
Fixes #1259.
Part of #1248.
> Fixes to PIO for newer netCDF library versions

- src/clib/pioc_support.c
Fixes #1283 
Parallel netcdf and netcdf4p may issue errors on tasks other than the ioroot, currently this would create a hang.   Also we cannot return at line 415 in any case since their are collective MPI calls later in the routine.
> handle pnetcdf/netcdf4p errors better

- CMakeLists.txt
- cmake_config.h.in
- examples/c/darray_no_async.c
- src/clib/pio.h
- src/clib/pio_darray_int.c
- src/clib/pio_file.c
- src/clib/pioc_support.c
- tests/cunit/test_darray.c
- tests/cunit/test_darray_frame.c
- tests/unit/basic_tests.F90
- tests/unit/driver.F90
pnetcdf has added a vard api which uses an MPI_DATATYPE as an input to describe the data.  This is implemented in cmake with PIO_USE_PNETCDF_VARD.   I've tested both with and without this feature and all tests pass on cheyenne with netcdf-mpi/4.4.1.1 and pnetcdf r3683
> Add pnetcdf vard2

- pio/pionfput_mod.F90.in
Making sure that NetCDF4-specific code is not built when 
using NetCDF libraries without support for NetCDF4.
Without the fix PIO1 build fails with NetCDF libs without
NetCDF4 support.
> Support NetCDF libs without NetCDF4 support

- src/flib/CMakeLists.txt
The passing of the defines for the MPI include path lacked
a dollar sign so it was not being expanded as a variable.
Therefore the actual include when compiling was `-IMPIF_H_PATH`.
This fixes #1307
> Bugfix to the MPI_HAS_MPIIO check.

- cmake/LibFind.cmake
Allows overload of environment variables like MPISERIAL_C_LIBRARY without it being set to NOTFOUND
> Do not overload user-defined PKGCOMPs

- configure.ac
- src/clib/pio_getput_int.c
- tests/cunit/Makefile.am
- tests/cunit/test_pioc.c
Due to a mistake I made netCDF 4.6.2 segfaults when presented with a NULL stride parameter. Whoops! Sorry about that. (It is fixed in netCDF for future releases, but 4.6.2 is out there.)
In this PR I use the same fake_stride solution formerly used for pnetcdf only. Now it is used for pnetcdf and netcdf.
This has been merged to develop for testing.
Fixes #1320.
Fixes #1326.
> Fix NULL bug

- tests/general/pio_decomp_tests_1d.F90.in
> removed mpi_scatter from only clause of use statement, which causes gfortran/mpich to error

- cmake/mpiexec.nwscla
- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pioc_support.c
- tests/cunit/test_darray.c
- tests/cunit/test_darray_multi.c
- tests/cunit/test_darray_multivar3.c
This removes the restrictions to data conversion at the netcdf/pnetcdf library level.   All tests pass but only because I removed a few expected failures.  I plan to add back some tests before merging to develop.  
Fixes #1334
> remove restrictions to data conversion

- pio/pio_types.F90
- pio/piodarray.F90.in
Add a pointer to the end of the linked list to avoid traversing the list each time add_data_to_buffer_{TYPE}  is called.
> optimize the linked list with a pointer to the list end

- configure.ac
This is to improve CI testing. The autotools build will no longer automatically build without pnetcdf if it is not found. It must be expressly disabled. This is to prevent tests seeming to pass for pnetcdf, but actually never being run, if pnetcdf is not properly found.
I have merged this to develop.
> add --disable-pnetcdf configure option and require it if pnetcdf is not found

- CMakeLists.txt
- src/clib/pio_internal.h
- src/clib/pio_msg.c
The issue was that all components were writing to the same memory location on the io root and so the value of msg could be overwritten at any point in the pio_msg_handler2.   The solution is to provide a unique location for each component to send messages to.   
All tests now pass with gnu/openmpi - test 30 test_darray_async_many is still timing out with
intel/mpt.
> Msg overwrite fix

- src/clib/pioc.c
Test program tests/cunit/test_async_simple.c, line 70 calls PIOc_init_async with argument component_count set to -1.
https://github.com/NCAR/ParallelIO/blob/bd08dcc9ce4f30b2c03f5d705496a1630a4a92d8/tests/cunit/test_async_simple.c#L70-L71
This negative value can cause an error for variable my_proc_list.
https://github.com/NCAR/ParallelIO/blob/bd08dcc9ce4f30b2c03f5d705496a1630a4a92d8/src/clib/pioc.c#L1336
> bug fix: allocate my_proc_list after checking component_count

- src/clib/pio_getput_int.c
- tests/cunit/test_async_perf.c
- tests/cunit/test_perf2.c
Fixes #1427.
No longer make compute processors wait for return code from data writes, allowing them to continue processing while writes are happening.
> Make async mode writes really async

- configure.ac
- doc/Doxyfile.in
- doc/Makefile.am
- src/flib/Makefile.am
- src/flib/piolib_mod.F90
- src/flib/pionfatt_mod.F90.in
Part of #1219.
In this PR I fix the last of the doxygen warnings with some autotools magic. The generated fortran files (from genf90.pl) don't have doxygen documentation. So I use sed after the fact in order to insert some, and suppress those warnings.
I have also added a check to the doc Makefile.am so that if there are any warnings, the documentation build fails. (This only matters when built with --enable-docs).
> fix last of doxygen warnings, new warnings will cause documentation build to fail

- configure.ac
- doc/Doxyfile.in
- doc/Makefile.am
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pio_msg.c
- src/clib/pio_rearrange.c
Part of #1219.
Now fixing --enable-developer-docs, in which all of C library code is included (but not all of the fortan code).
No code changes in this PR, just documentation.
> documentation fix for --enable-developer-docs

- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_nc.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- src/flib/pio_kinds.F90
- src/flib/piolib_mod.F90
Part of #1219.
@jedwards4b I am starting to make changes to F90 files, and I want to get you to take a look before I proceed further.
Emacs is wanting me to indent comments to the same column as the code, is that a problem?
For example:
```
!>
!! @public
!! @ingroup PIO_getnumiotasks
!! @brief This returns the number of IO-tasks that PIO is using
!! @param iosystem : a defined pio system descriptor, see PIO_types
!! @param numiotasks : the number of IO-tasks
!<
subroutine getnumiotasks(iosystem,numiotasks)
```
becomes:
```
!>
!! @public
!! @ingroup PIO_getnumiotasks
!! @brief This returns the number of IO-tasks that PIO is using
!! @param iosystem : a defined pio system descriptor, see PIO_types
!! @param numiotasks : the number of IO-tasks
!<
subroutine getnumiotasks(iosystem,numiotasks) …
```
> more documentation work, including some fortran code

- Makefile.am
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pio_rearrange.c
- src/clib/pioc_support.c
- tests/performance/pioperformance.F90
Part of #1485, #1480, #1484.
Fixes #1478.
Isolating the GPTL code to make it easier to debug and replace, if we decide to do that.
> isolating GPTL calls

- configure.ac
- examples/c/Makefile.am
- examples/c/darray_no_async.c
- examples/c/example1.c
- examples/c/examplePio.c
- src/clib/pio_darray.c
- src/clib/pio_file.c
- src/clib/pio_internal.h
- src/clib/pio_msg.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/cunit/Makefile.am
- tests/cunit/pio_tests.h
- tests/cunit/test_async_multicomp.c
- tests/cunit/test_common.c
- tests/cunit/test_darray.c
- tests/cunit/test_darray_async_simple.c
- tests/cunit/test_perf2.c
Part of #1488.
After this PR, when PIO and the whole I/O stack are built with gcc -llmpe -lmpe -lmpi -lpthread (instead of mpicc), then MPE logging is automatically turned on for every PIO program.
I will put some output in the issue for illustration.
Of course this only works if MPE is installed and --enable-mpe is used at configure.
> Basic MPE logging capability

- src/clib/Makefile.am
- src/clib/pio_error.h
- src/clib/pio_internal.h
- src/clib/pio_rearrange.c
- tests/cunit/pio_tests.h
Part of #1500.
I am trying to move some stack allocations to heap. This means we need slightly more sophisticated error handling in some functions, in order to clean up our memory before leaving the function on error.
The method is the same as is used in the netcdf-c library. An exit label is added and all allocations freed after that. Instead of returning an error code, the code calls macro EXIT() with the error code. This calls pio_err() and then goes to exit to free memory and return the error code.
Note some important parts of this idiom:
* The var "ret" is used for return codes.
* ret must be initialized to PIO_NOERR.
* All pointers that will receive memory allocations must be initialized to NULL.
> Clean up of error handling macros

- src/flib/Makefile.am
- src/flib/piolib_mod.F90
- src/flib/pionfatt_mod.F90.in
- tests/unit/basic_tests.F90
- tests/unit/ncdf_tests.F90
Fixes #1504 
Fixes #1508 
Fixes #1513 
Fixes #1507 
Some fixes for Fortran warnings. Warnings are a reminder that programmers need to work harder. Soon we will have a warning-free build, I hope, and we can enforce that in Travis.
> fix some fortran warnings

- src/ncint/ncintdispatch.c
- src/ncint/ncintdispatch.h
Part of #1556 
This PR contains mapping for the rest of the PIO functions into the netcdf integration. All remaining functions in the dispatch table are not implement in PIO.
> Rest of PIO functions in netcdf integration

- configure.ac
- src/flib/Makefile.am
- src/flib/ncint_mod.F90
- src/flib/pio.F90
- src/flib/piolib_mod.F90
Part of #1555.
In this PR I move the netcdf integration code in Fortran out of piolib_mod.F90 and into new file ncint_mod.F90. This allows the code for the new nf_ functions to be kept separate from the rest of the PIO functions, which all start with PIO_.
> moved netcdf integration to separate fortran file ncint_mod.F90

- src/flib/ncint_mod.F90
Part of #1555.
Adding function nf_free_iosystem to the fortran API for netCDF integration.
> more work on netcdf fortran pio integration - adding nf_free_iosystem()

- src/clib/pio.h
- src/clib/pioc_support.c
- src/flib/ncint_mod.F90
- src/flib/pio.F90
- src/ncint/ncint_pio.c
- tests/fncint/ftst_pio.f90
- tests/ncint/tst_pio_udf.c
Part of #1555.
Getting nf_free_iosystem() to work better.
> getting nf_free_iosystem working in fortran API

- src/flib/ncint_mod.F90
- tests/fncint/ftst_pio.f90
Part of #1555.
To match the netCDF Fortran 77 api, all nf_* calls should be functions that return an integer. In this PR I convert nf_init_intracom and nf_free_iosystem to functions.
> converted nf_ procedures into functions

- src/flib/ncint_mod.F90
- src/ncint/ncintdispatch.c
- tests/fncint/ftst_pio.f90
- tests/ncint/tst_pio_udf.c
Part of #1555.
This fixes a memory leak in the netCDF integration layer. This code only builds with --enable-netcdf-integration, and requires the current netCDF master plus an outstanding PR (https://github.com/Unidata/netcdf-c/pull/1440).
This will have no effect on current users or the build of PIO without --enable-netcdf-integration.
> Fixing a memory leak in the netCDF integration layer

- configure.ac
- doc/source/netcdf_integration.txt
- doc/source/users_guide.txt
- src/clib/pio.h
- src/clib/pio_file.c
- src/clib/pioc_support.c
- src/flib/Makefile.am
- src/flib/ncint_mod.F90
- src/flib/pio.F90
- src/ncint/ncint_pio.c
- src/ncint/ncintdispatch.h
- tests/fncint/ftst_pio.f90
- tests/ncint/tst_pio_udf.c
Part of #1555.
In this PR:
* the rest of tst_pio_udf.c is turned back on. Now there are no memory leaks.
* Functions nc/nf_init_intracom and nc/nf_init_decomp are renamed to nc/nf_def_iosystem, nc/nf_def_decomp.
* Beginning to add documentation for netcdf integration features.
> Turn on rest of ncint C test, now with no leaks, change some function names, begin to add docs

- src/flib/ncint_mod.F90
- src/flib/pio.F90
- src/flib/piolib_mod.F90
- tests/fncint/ftst_pio.f90
Part of #1555.
nf_def_decomp() added to fortran API in support of netcdf integration.
> nf_def_decomp() added to fortran API in support of netcdf integration

- src/flib/ncint_mod.F90
- src/flib/pio.F90
- src/ncint/nc_put_vard.c
- tests/fncint/Makefile.am
- tests/fncint/ftst_pio.f90
- tests/fncint/ftst_pio_orig.f90
- tests/fncint/run_tests.sh
Part of #1555.
Changes to the netcdf integration functions in fortran to use IDs instead of custom PIO types iodesc_t and iosystem_t.
Starting to get the vard functions working in the fortran API.
> starting to get nf_put_vard_* functions working

- src/clib/pio_darray_int.c
- src/flib/ncint_mod.F90
- tests/fncint/Makefile.am
- tests/fncint/ftst_pio.f90
- tests/fncint/ftst_pio_orig.f90
- tests/fncint/run_tests.sh
- tests/fncint/tst_c_pio.c
Part of #1555.
In this PR, I add some test code. One of the tests, ftst_pio.f90, uses netCDF integration to use PIO from netcdf fortran code, with a distributed array write.
> now getting darray write working in fortran with netcdf integration

- src/clib/pio_darray.c
When writing with netcdf or netcdf4c the ioroot buffer must be maxiobuflen so that it can receive from all iotasks.
> must allocate on ioroot for serial io

- Makefile.am
- cmake/Makefile.am
- configure.ac
- examples/Makefile.am
- examples/c/CMakeLists.txt
- examples/c/Makefile.am
- src/clib/Makefile.am
- src/gptl/Makefile.am
- tests/cunit/Makefile.am
- tests/unit/Makefile.am
After this PR, the cmake builds works from the autotools distribution.
Part of #1585
> fix cmake build in autotools dist

- src/clib/pioc_support.c
- tests/fncint/Makefile.am
Part of #1555.
Some minor fixes in support of some CI jobs. In this PR I fix a doc problem and turn on fortran netcdf integration tests.
> Some minor fixes to netcdf integration code to get it past all my CI jobs

- src/clib/pio.h
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pio_lists.c
- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/cunit/test_async_1d.c
- tests/cunit/test_darray.c
- tests/cunit/test_spmd.c
- tests/ncint/tst_pio_async.c
- tests/ncint/tst_pio_udf.c
Fixes #1599 
We know the value of ndims for each var when we open a file or define a var. So we just need to remember it instead of looking it up again later. This will make #1598 easier.
> Now store ndims in var_desc_t struct; we no longer need to look it up in read_darray()

- doc/source/base.txt
- doc/source/netcdf_integration.txt
- src/clib/pio.h
- src/clib/pio_file.c
- tests/ncint/tst_pio_async.c
- tests/ncint/tst_pio_udf.c
Part of #1555 
Adding some documentation for netCDF integration. More to come. 
Also adding NC_PIO as a synonym for NC_UDF0, to make the code look more pretty.
Also changed the starting ncid of PIO files to 128, to  allow users to open files with and without netCDF PIO integration, at the same time. (Confusing!)
> version 1 of netcdf integration documentation

- src/clib/pioc.c
`PIOc_InitDecomp_bc()` computes a zero-based `compmap` and passes it to `PIOc_InitDecomp()`, which expects a one-based `compmap`.
> Fix an off-by-one error in PIOc_InitDecomp_bc()

- src/clib/CMakeLists.txt
This pull request fixes #1551 in the CMake build system (#1552 did the same for autoconf).
Note that relative paths specified in `install(FILES ...)` are interpreted as relative to the current source directory, so `${CMAKE_CURRENT_SOURCE_DIR}` is not needed.
> Install uthash.h when building ParallelIO using CMake

- src/clib/pio.h
- src/clib/pio_internal.h
Fixes #1608 
In this PR I move some code that depends on ifdefs out of pio.h.
pio.h is our public header, we cannot count on these ifdefs being defined by the user. We must confine out use of these ifdefs to files that include config.h, and our public header cannot include that file.
> move reliance on ifdefs out of pio.h

- src/clib/pio.h
Fixes #1576 
Some more ifdefs that should not be in pio.h.
> removed more inappropriate ifdefs from pio.h

- src/clib/pio.h
- src/clib/pio_nc.c
- src/clib/pioc_support.c
- tests/ncint/Makefile.am
- tests/ncint/pio_err_macros.h
- tests/ncint/run_perf.sh
- tests/ncint/tst_ncint_perf.c
Fixes #1617 
After this PR, when opening a netCDF-4/HDF5 file in sequential mode using netCDF integration, then deflate will no longer be automatically turned on.
Existing PIOc_* code is not affected by this change. Only new code, written to use the netCDF integration features, will be affected.
Also in this PR I added a performance testing program tests/ncint/tst_ncint_perf.c.
> For netCDF integration opens/creates of PIO_IOTYPE_NETCDF4C, don't automatically turn on deflation for every var

- src/clib/pio_msg.c
Fixes #1633 
These warnings were a result of the netCDF integration code. I have made some changes so the warnings do not appear.
> fixed warnings related to netcdf integration code

- src/clib/pioc.c
Adding an if in a PIO_ENABLE_LOGGING clause to prevent core dump when rindex is not allocated.
> if rindex is null and debug is enabled this will segfault

- src/clib/pio_nc4.c
- tests/unit/ncdf_tests.F90
Fixes #1643 
Change a test to stop testing deflate levels. Due to a bug, netcdf-c-4.7.4 can't set the deflate level twice to different values.
> changed test to always use deflate of 1

- CMakeLists.txt
- src/clib/CMakeLists.txt
- src/clib/Makefile.am
- src/clib/pio_error.c
- src/clib/pio_error.h
- tests/cunit/test_common.c
- tests/general/CMakeLists.txt
This is #1662 with the Makefile.am fix.
> Fix multiple definition errors with GCC>=10.1.0

- CMakeLists.txt
- src/clib/CMakeLists.txt
- src/clib/pio_error.c
- src/clib/pio_error.h
- tests/cunit/test_common.c
- tests/general/CMakeLists.txt
This patch fixes #1651 by properly separating declarations of global variables in C headers from their definitions which are now moved to a separate .c compilation unit.  The original code cause the C compiler to add a new (strong) symbol for `err_buffer` and `resultlen` to every compilation unit that includes `pio_error.h`.
> Fix multiple definition errors with GCC>=10.1.0 

- CMakeLists.txt
> fixed creation of config.h on read-only filesystem

- .github/workflows/a3.yml
- CMakeLists.txt
- cmake/LibMPI.cmake
- configure.ac
- examples/c/run_tests.sh.in
- tests/cunit/run_tests.sh.in
Fixes  #1732 
Fixes #1282
Fixes #1423
Fixes #1730
Part of #1675 
Currently the netcdf-4.7.4_pnetcdf-12.1_ncint_openmpi_4.0.4 test only builds with autotools, the C library and tests only. In this PR I add CMake builds of the C library as well.
With openmpi, this means the --with-mpiexec= option must be working, so that I can pass the --oversubscribe option to mpiexec.
> Adding cmake build of C library to openmpi GitHub actions testing workflow, also allow setting of mpiexec command at configure

- configure.ac
- src/clib/CMakeLists.txt
Fixes #1686 
In this PR I remove the last two flags set by our cmake build which are not in config.h. The defines were never used in any code anyway.
Config.h is our one-stop shopping for all pre-processor defines, in C and Fortran.
> removed unused VARN pre-processor defines

- src/clib/pio_nc4.c
- src/ncint/ncintdispatch.c
- src/ncint/ncintdispatch.h
- tests/ncint/CMakeLists.txt
- tests/ncint/Makefile.am
- tests/ncint/run_tests.sh.in
- tests/ncint/tst_var_compress.c
Part of #1654 
Adding functions to netCDF implementation layer for variable deflate settings.
nc_inq_var_chunking is still not working, and I will also add some fortran tests...
> Adding deflate to netCDF integration layer

- src/clib/pio_nc.c
Fixes #1632 
Now compression must be explicitly turned on in all cases, it is not turned on automatically.
> no longer turn on deflate for vars automatically

- examples/c/example1.c
- examples/c/example2.c
Make the example err_buffer variable unique from that in pio_error.h to avoid namespace conflicts. 
Fixes #1773
> make example err_buffers distinct names from that in pio_error.h

- CMakeLists.txt
Fixes #1780 
Use the WITH_PNETCDF option in CMakeLists.txt
> use WITH_PNETCDF in CMake build

- src/clib/pio_darray.c
- src/clib/pio_msg.c
pio_sorted_copy should only be called on compute tasks. 
Fixes #1786
> array sort should only happen on compute tasks

- src/clib/pio_msg.c
- src/clib/pioc_support.c
- tests/general/pio_iosystem_async_tests.F90.in
Use MPI_WAITSOME instead of MPI_WAITANY to avoid message starving.  This was inspired by a note to users in the mpi standard :
> A server with multiple clients can use MPI_WAITSOME so as not to starve any client. Clients send messages to the server with service requests. The server calls MPI_WAITSOME with one receive request for each client, and then handles all receives that completed. If a call to MPI_WAITANY is used instead, then one client could starve while requests from another client always sneak in first. ( End of advice to users.) 
Fixes #1801
> change waitany to waitsome to avoid message starving

- src/clib/pio_error.h
- tests/cunit/test_async_1d.c
- tests/cunit/test_async_3proc.c
- tests/cunit/test_async_4proc.c
- tests/cunit/test_async_manyproc.c
- tests/cunit/test_async_multi2.c
- tests/cunit/test_async_multicomp.c
- tests/cunit/test_async_perf.c
- tests/cunit/test_async_simple.c
- tests/cunit/test_darray_2sync.c
- tests/cunit/test_darray_async.c
- tests/cunit/test_darray_async_from_comm.c
- tests/cunit/test_darray_async_many.c
- tests/cunit/test_darray_async_simple.c
- tests/ncint/pio_err_macros.h
Fixes #1792 
Fixed error handling in async tests. Instead of calling MPI_finalize(), call PIOc_finalize() to tell the I/O processes to exit their loop. This causes the test to return as failed, instead of just hanging.
> fix error handling in async tests

- .github/workflows/cmake_netcdf-4.7.4_hdf5-1.10.7_pnetcdf-12.1_ncint_mpich-3.3_asan.yml
Fixes #1728 
Some changes to the cmake build. It was being run twice, once without fortran, then with fortran. Also, when it was built with fortran, only one test was being run.
Now it builds one, with fortran, and runs all tests.
> fixing cmake workflow

- src/flib/pionfput_mod.F90.in
cce 10.0.3 caught an inconsistancy in the declaration of PIOc_put_var_
```
ftn-828 crayftn: ERROR PIOC_PUT_VAR_INT, File = ../../../global/cscratch1/sd/jedwards/foo/bld/cray/mpt/nodebug/nothreads/mct/pio/pio2/src/flib/pionfput_mod.F90, Line = 246, Column = 62 
Procedure "PIOc_put_var_int" is defined in multiple places.  Argument 3 has INTENT(IN) in one definition but not the other.
```
this fixes the issue.
> fix inconsistancy in intent

- CMakeLists.txt
Only do fortran related cmake functions if building the fortran interface.
Tested with both possible values of PIO_ENABLE_FORTRAN
> only do cmake fortran if building fortran interface

- src/clib/CMakeLists.txt
- src/clib/pio.h
- src/clib/pio_darray.c
- src/clib/pio_darray_int.c
- src/clib/pio_internal.h
- src/clib/pio_nc.c
- src/clib/pio_rearrange.c
- src/clib/pioc.c
- src/clib/pioc_support.c
- tests/CMakeLists.txt
- tests/cperf/CMakeLists.txt
- tests/cperf/mpi_argp.c
- tests/cperf/piodecomptest.c
- tests/cunit/test_darray_async.c
Refactors the subset decomposition method to support multiple destinations for each source when reading.  This allows for example halo regions to be populated.    This method so far only works for the subset rearranger and the mapping file cannot be used for write since it would be in-determinant to have multiple sources for the same destination.
> Refactor subset method

- src/flib/piolib_mod.F90
Fixes #281 I did this with an optional field to maintain backward compatiblity.
> fortran pio_deletefile return code, optional for backward compatiblity

- src/clib/pio_internal.h
> remove the redefinition of MPI_Offset and MPI_OFFSET

- .github/workflows/cmake.yml
- .github/workflows/cmake_ncint.yml
- CMakeLists.txt
- cmake_config.h.in
- configure.ac
- ctest/CTestEnvironment-anlworkstation.cmake
- src/clib/pio_rearrange.c
- src/clib/pioc.c
- src/clib/pioc_support.c
> update minimum cmake version, based on the oldest I can access

- src/clib/pioc.c
This allocation may be too large for the stack, moving to heap.
> move this allocation to the heap

- CMakeLists.txt
ESMF has a requirement to work with cmake 3.5.2, this change allows the older version.
> make work with cmake 3.5.2 (esmf requirement)

- .github/actions/buildhdf5/action.yml
- .github/actions/buildmpich/action.yml
- .github/actions/buildnetcdf/action.yml
- .github/actions/buildnetcdff/action.yml
- .github/actions/buildopenmpi/action.yml
- .github/actions/buildpnetcdf/action.yml
- .github/actions/intelcompilers/action.yml
- .github/actions/parallelio_autotools/action.yml
- .github/actions/parallelio_cmake/action.yml
- .github/workflows/autotools.yml
- .github/workflows/cmake.yml
- .github/workflows/cmake_ubuntu_latest.yml
- .github/workflows/intel.yml
- .github/workflows/netcdf_hdf5_no_pnetcdf_ncint_mpich.yml
- .github/workflows/netcdf_hdf5_pnetcdf_ncint_mpich_asan.yml
- .github/workflows/netcdf_pnetcdf_openmpi.yml
- .github/workflows/strict_autotools_ubuntu_latest.yml
- .github/workflows/withspack.yml
- CMakeLists.txt
- src/clib/parallel_sort.c
- src/clib/pio_rearrange.c
- tests/cunit/CMakeLists.txt
squash commit of external_actions pr.
> squash commit of external_actions

- examples/basic/kinds_mod.F90
- src/gptl/perf_utils.F90
Remove protex markups, ParallelIO does not use protex and they cause issues in ESMF.
> remove unused protex markups

- src/clib/pio_nc4.c
This PR fixes minor bugs in src/clib/pio_nc4.c that prevent compilation in DEBUG mode.
> fix minor bugs in pio_nc4.c

- src/clib/CMakeLists.txt
- src/clib/pioc_support.c
[See my PR for ESMF](https://github.com/esmf-org/esmf/pull/348). ESMF uses ParallelIO, and it fails to build through cygwin because of a few small issues in ParallelIO. Here, I try to address those:
- In the src/clib/CMakeLists.txt, there is a check that long long and size_t are the same size. On cygwin, these sizes cannot be retrieved, which makes them both empty strings. This causes the check to fail, because empty strings cannot be parsed as numbers so ${SIZEOF_SIZE_T} EQUAL ${SIZEOF_LONG_LONG} evaluates to false in CMake. I modified the check to simply test if they are the same, not if they are parsable numbers and the same.
- In the src/clib/pioc_support.c there is an include of execinfo.h. This header is missing on many platforms, including Cygwin. I have added a more portable check …
> Fix issues that prevent compilation in Cygwin

- CMakeLists.txt
There is some logic in the CMakeLists.txt file that checks the name of the C compiler to determine if it is the GNU compiler. This logic should be changed to check the name of the Fortran compiler instead. This is important on a Mac where the C compiler is clang and the Fortran compiler is gfortran.
Without this change, I was getting build failures on my Mac in gptl and the tests. This change resolved those build failures (changing warnings to errors).
> Check Fortran compiler name instead of C compiler name

- doc/source/Installing.txt
- src/clib/CMakeLists.txt
- src/flib/CMakeLists.txt
- src/gptl/CMakeLists.txt
- tests/CMakeLists.txt
Updates CMake version requirement from 2.8.12 to 3.5.2 in all files. Fixes [issue](https://github.com/NCAR/ParallelIO/issues/2006) with CMake 4.0.0.
> Bump CMake required version to 3.5.2
